#include "ApBootstrap.hpp"
namespace Davis::ApBootstrap {
static i32 Find(const State&s,u32 id){for(u32 i=0;i<s.count;i++)if(s.cpu[i].apicId==id)return (i32)i;return -1;}
static u64 Token(u32 apic,u32 logical,u64 entry){u64 x=0xD415A9B0075A11ull^((u64)apic<<32)^logical^entry;x^=x>>29;x*=0x9E3779B185EBCA87ull;x^=x>>31;return x?x:1;}
bool Init(const SmpTopology::State&t,u64 base,u64 bytes,u64 entry,State&s){s={};if(!t.ready||!t.cpuCount||!entry||bytes<MinStackBytes||bytes>MaxStackBytes||(bytes&0xfffull)||(base&0xfffull))return false;if(base+bytes*t.cpuCount<base)return false;for(u32 i=0;i<t.cpuCount;i++){auto &d=s.cpu[i];d.apicId=t.cpus[i].apicId;d.logicalId=i;d.stackBase=base+(u64)i*bytes;d.stackTop=d.stackBase+bytes;d.entryPoint=entry;d.token=Token(d.apicId,i,entry);d.stage=(i==t.bspIndex)?Stage::Online:Stage::Prepared;if(d.stage==Stage::Online)s.online++;s.count++;}s.generation=1;s.ready=true;return Validate(s);}
bool StartupSent(State&s,SmpTopology::State&t,u32 id){i32 i=Find(s,id);if(i<0)return false;auto&c=s.cpu[i];if(c.stage!=Stage::Prepared&&c.stage!=Stage::Failed)return false;if(c.attempts>=SmpTopology::MaxStartupAttempts)return false;if(!SmpTopology::BeginStartup(t,(u32)i))return false;c.attempts++;c.stage=Stage::StartupSent;s.generation++;return true;}
bool EnteredLongMode(State&s,u32 id,u64 token){i32 i=Find(s,id);if(i<0)return false;auto&c=s.cpu[i];if(c.stage!=Stage::StartupSent||c.token!=token)return false;c.stage=Stage::EnteredLongMode;s.generation++;return true;}
bool Rendezvous(State&s,u32 id,u64 token){i32 i=Find(s,id);if(i<0)return false;auto&c=s.cpu[i];if(c.stage!=Stage::EnteredLongMode||c.token!=token)return false;c.stage=Stage::Rendezvous;s.generation++;return true;}
bool MarkOnline(State&s,SmpTopology::State&t,SmpRuntime::State&r,u32 id,u64 token){i32 i=Find(s,id);if(i<0)return false;auto&c=s.cpu[i];if(c.stage==Stage::Online)return true;if(c.stage!=Stage::Rendezvous||c.token!=token)return false;if(!SmpTopology::MarkOnline(t,id))return false;if(!SmpRuntime::SetOnline(r,id,true))return false;c.stage=Stage::Online;s.online++;s.generation++;return Validate(s)&&SmpRuntime::Validate(r);}
bool MarkFailed(State&s,SmpTopology::State&t,u32 id){i32 i=Find(s,id);if(i<0)return false;auto&c=s.cpu[i];if(c.stage!=Stage::StartupSent&&c.stage!=Stage::EnteredLongMode&&c.stage!=Stage::Rendezvous)return false;if(!SmpTopology::MarkFailed(t,id))return false;c.stage=Stage::Failed;s.generation++;return true;}
const CpuBoot* Lookup(const State&s,u32 id){i32 i=Find(s,id);return i<0?nullptr:&s.cpu[i];}
bool Validate(const State&s){if(!s.ready||!s.count||s.count>MaxCpus||!s.online||s.online>s.count)return false;u32 on=0;for(u32 i=0;i<s.count;i++){const auto&c=s.cpu[i];if(c.logicalId!=i||!c.entryPoint||!c.token||c.stackTop<=c.stackBase||(c.stackBase&0xfffull)||(c.stackTop&0xfffull))return false;for(u32 j=i+1;j<s.count;j++)if(c.apicId==s.cpu[j].apicId)return false;if(c.stage==Stage::Online)on++;}return on==s.online;}
}
