#include "AudioMedia.hpp"
namespace Davis::AudioMedia {
static u16 le16(const u8*p){return (u16)(p[0]|((u16)p[1]<<8));}
static u32 le32(const u8*p){return (u32)p[0]|((u32)p[1]<<8)|((u32)p[2]<<16)|((u32)p[3]<<24);}
static u32 be24(const u8*p){return ((u32)p[0]<<16)|((u32)p[1]<<8)|p[2];}
static bool four(const u8*p,char a,char b,char c,char d){return p[0]==(u8)a&&p[1]==(u8)b&&p[2]==(u8)c&&p[3]==(u8)d;}
static bool mp3sync(const u8*p,u32 n){return n>=4&&p[0]==0xff&&(p[1]&0xe0)==0xe0&&(p[1]&0x18)!=0x08&&(p[2]&0xf0)!=0xf0&&(p[2]&0x0c)!=0x0c;}
Codec Detect(const u8*d,u32 n){if(!d)return Codec::Unknown;if(n>=12&&four(d,'R','I','F','F')&&four(d+8,'W','A','V','E'))return Codec::WavPcm;if(n>=4&&four(d,'f','L','a','C'))return Codec::Flac;u32 p=0;if(n>=10&&d[0]=='I'&&d[1]=='D'&&d[2]=='3'){u32 s=((d[6]&127u)<<21)|((d[7]&127u)<<14)|((d[8]&127u)<<7)|(d[9]&127u);p=10+s;}if(p<n&&mp3sync(d+p,n-p))return Codec::Mp3;return Codec::Unknown;}
static bool probeWav(const u8*d,u32 n,Info&o){u32 p=12;bool fmt=false,data=false;u16 af=0,ba=0;while(p+8<=n){u32 sz=le32(d+p+4),body=p+8;if(body>n||sz>n-body)return false;if(four(d+p,'f','m','t',' ')){if(sz<16)return false;af=le16(d+body);o.channels=le16(d+body+2);o.sampleRate=le32(d+body+4);ba=le16(d+body+12);o.bitsPerSample=le16(d+body+14);fmt=true;}else if(four(d+p,'d','a','t','a')){o.dataOffset=body;o.dataBytes=sz;data=true;}u64 next=(u64)body+sz+(sz&1u);if(next>n)return false;p=(u32)next;if(fmt&&data)break;}if(!fmt||!data||af!=1||!(o.channels==1||o.channels==2)||!(o.bitsPerSample==8||o.bitsPerSample==16||o.bitsPerSample==24||o.bitsPerSample==32)||!o.sampleRate||!ba)return false;u32 expected=o.channels*(o.bitsPerSample/8);if(ba!=expected||o.dataBytes<ba)return false;o.codec=Codec::WavPcm;o.totalFrames=o.dataBytes/ba;return true;}
static bool probeFlac(const u8*d,u32 n,Info&o){if(n<42)return false;u32 p=4;bool got=false;while(p+4<=n){bool last=(d[p]&0x80)!=0;u8 type=d[p]&0x7f;u32 len=be24(d+p+1);p+=4;if(len>n-p)return false;if(type==0){if(len<34)return false;const u8*s=d+p;u64 x=((u64)s[10]<<56)|((u64)s[11]<<48)|((u64)s[12]<<40)|((u64)s[13]<<32)|((u64)s[14]<<24)|((u64)s[15]<<16)|((u64)s[16]<<8)|s[17];o.sampleRate=(u32)((x>>44)&0xfffff);o.channels=(u16)(((x>>41)&7)+1);o.bitsPerSample=(u16)(((x>>36)&31)+1);o.totalFrames=x&0xfffffffffull;got=true;}p+=len;if(last){o.dataOffset=p;o.dataBytes=n-p;break;}}if(!got||!o.dataOffset||!o.sampleRate||!(o.channels==1||o.channels==2)||o.bitsPerSample<4||o.bitsPerSample>24)return false;o.codec=Codec::Flac;return true;}
static bool probeMp3(const u8*d,u32 n,Info&o){u32 p=0;if(n>=10&&d[0]=='I'&&d[1]=='D'&&d[2]=='3'){u32 s=((d[6]&127u)<<21)|((d[7]&127u)<<14)|((d[8]&127u)<<7)|(d[9]&127u);p=10+s;}if(p+4>n||!mp3sync(d+p,n-p))return false;u8 ver=(d[p+1]>>3)&3,sri=(d[p+2]>>2)&3,mode=(d[p+3]>>6)&3;static const u32 sr[3]={44100,48000,32000};if(sri==3)return false;u32 rate=sr[sri];if(ver==2)rate/=2;else if(ver==0)rate/=4;else if(ver!=3)return false;o.codec=Codec::Mp3;o.sampleRate=rate;o.channels=mode==3?1:2;o.bitsPerSample=16;o.dataOffset=p;o.dataBytes=n-p;o.totalFrames=0;return rate!=0;}
bool Probe(const u8*d,u32 n,Info&o){o={};switch(Detect(d,n)){case Codec::WavPcm:return probeWav(d,n,o);case Codec::Flac:return probeFlac(d,n,o);case Codec::Mp3:return probeMp3(d,n,o);default:return false;}}

struct Bits{const u8*d;u32 n,bit;bool ok;};
static u32 rb(Bits&b,u32 k){if(k>32||b.bit+(u64)k>(u64)b.n*8){b.ok=false;return 0;}u32 v=0;while(k--){v=(v<<1)|((b.d[b.bit>>3]>>(7-(b.bit&7)))&1);b.bit++;}return v;}
static i32 rs(Bits&b,u32 k){if(!k)return 0;u32 v=rb(b,k);if(!b.ok)return 0;if(k<32&&(v&(1u<<(k-1))))v|=(~0u<<k);return (i32)v;}
static bool utf8int(Bits&b,u64&v){u8 x=(u8)rb(b,8);if(!b.ok)return false;if(!(x&0x80)){v=x;return true;}u32 more=0;u8 mask=0x80;while(x&mask){more++;mask>>=1;}if(more<2||more>7)return false;v=x&((1u<<(7-more))-1);for(u32 i=1;i<more;i++){u8 y=(u8)rb(b,8);if((y&0xc0)!=0x80)return false;v=(v<<6)|(y&0x3f);}return true;}
static bool residual(Bits&b,i32*out,u32 block,u32 warm){u32 method=rb(b,2);if(method>1)return false;u32 order=rb(b,4),parts=1u<<order;if(!b.ok||!parts||block%parts)return false;u32 partN=block/parts,at=warm;for(u32 p=0;p<parts;p++){u32 n=partN;if(p==0){if(n<warm)return false;n-=warm;}u32 rice=rb(b,method?5:4),escape=method?31:15;if(rice==escape){u32 raw=rb(b,5);for(u32 i=0;i<n;i++)out[at++]=raw?rs(b,raw):0;}else{for(u32 i=0;i<n;i++){u32 q=0;while(b.ok&&rb(b,1)==0){if(++q>0x00ffffffu){b.ok=false;break;}}u32 rem=rice?rb(b,rice):0;u32 u=(q<<rice)|rem;out[at++]=(i32)((u>>1)^((u&1)?0xffffffffu:0));}}}return b.ok&&at==block;}
static bool subframe(Bits&b,i32*out,u32 block,u32 bps){if(rb(b,1)!=0)return false;u32 type=rb(b,6);bool wasted=rb(b,1)!=0;if(wasted){u32 z=0;while(b.ok&&rb(b,1)==0){if(++z>31)return false;}bps-=z+1;if(!bps)return false;}if(type==0){i32 v=rs(b,bps);for(u32 i=0;i<block;i++)out[i]=v;}
 else if(type==1){for(u32 i=0;i<block;i++)out[i]=rs(b,bps);}
 else if(type>=8&&type<=12){u32 o=type-8;if(o>block)return false;for(u32 i=0;i<o;i++)out[i]=rs(b,bps);if(!residual(b,out,block,o))return false;for(u32 i=o;i<block;i++){i64 v=out[i];if(o==1)v+=out[i-1];else if(o==2)v+=2ll*out[i-1]-out[i-2];else if(o==3)v+=3ll*out[i-1]-3ll*out[i-2]+out[i-3];else if(o==4)v+=4ll*out[i-1]-6ll*out[i-2]+4ll*out[i-3]-out[i-4];out[i]=(i32)v;}}
 else if(type>=32){u32 o=(type&31)+1;if(o>32||o>block)return false;for(u32 i=0;i<o;i++)out[i]=rs(b,bps);u32 prec=rb(b,4)+1;if(prec==16)return false;i32 sh=rs(b,5);i32 coef[32];for(u32 i=0;i<o;i++)coef[i]=rs(b,prec);if(!residual(b,out,block,o))return false;for(u32 i=o;i<block;i++){i64 sum=0;for(u32 j=0;j<o;j++)sum+=(i64)coef[j]*out[i-j-1];i64 pred=sh>=0?(sum>>sh):(sum<<(-sh));out[i]=(i32)((i64)out[i]+pred);}}
 else return false;
 if(wasted){/* determine wasted shift from unary field by reparsing is undesirable; FLAC wasted-bits is rare. Reject safely for now. */return false;}return b.ok;}
static bool decodeFlacFrame(Decoder&x){if(x.pos+6>x.bytes)return false;Bits b{x.data+x.pos,x.bytes-x.pos,0,true};if(rb(b,14)!=0x3ffe||rb(b,1)!=0)return false;rb(b,1);u32 bs=rb(b,4),sr=rb(b,4),ca=rb(b,4),ss=rb(b,3);if(rb(b,1)!=0||!b.ok||ca>10||ss==3||ss==7)return false;u64 num=0;if(!utf8int(b,num))return false;u32 block=0;if(bs==1)block=192;else if(bs>=2&&bs<=5)block=576u<<(bs-2);else if(bs==6)block=rb(b,8)+1;else if(bs==7)block=rb(b,16)+1;else if(bs>=8)block=256u<<(bs-8);else return false;if(!block||block>MaxFlacBlock)return false;if(sr==12)rb(b,8);else if(sr==13||sr==14)rb(b,16);rb(b,8); /* header CRC8, structural boundary only */
 u32 bps=x.info.bitsPerSample;if(ss==1)bps=8;else if(ss==2)bps=12;else if(ss==4)bps=16;else if(ss==5)bps=20;else if(ss==6)bps=24;
 static i32 ch0[MaxFlacBlock],ch1[MaxFlacBlock];u32 channels=(ca<=7)?ca+1:2;if(channels!=x.info.channels||channels>2)return false;u32 b0=bps,b1=bps;if(ca==8)b1++;else if(ca==9)b0++;else if(ca==10)b1++;
 if(!subframe(b,ch0,block,b0))return false;if(channels==2&&!subframe(b,ch1,block,b1))return false;b.bit=(b.bit+7)&~7u;if(b.bit+16>(u64)b.n*8)return false;rb(b,16);if(!b.ok)return false;
 for(u32 i=0;i<block;i++){i32 l=ch0[i],r=channels==2?ch1[i]:ch0[i];if(ca==8)r=l-r;else if(ca==9)l=l+r;else if(ca==10){i64 mid=l,side=r;mid=(mid<<1)|(side&1);l=(i32)((mid+side)>>1);r=(i32)((mid-side)>>1);}x.flacPcm[i*2]=l;x.flacPcm[i*2+1]=r;}x.flacIndex=0;x.flacCount=block;x.pos+=(b.bit>>3);return true;}

bool Open(Decoder&x,const u8*d,u32 n){x={};if(!d||!Probe(d,n,x.info))return false;if(x.info.codec!=Codec::WavPcm&&x.info.codec!=Codec::Flac)return false;x.data=d;x.bytes=n;x.pos=x.info.dataOffset;x.open=true;return true;}
u64 TellFrame(const Decoder&x){if(!x.open)return 0;if(x.info.codec==Codec::Flac)return x.framePos;if(x.pos<x.info.dataOffset)return 0;u32 ba=x.info.channels*(x.info.bitsPerSample/8);return ba?(x.pos-x.info.dataOffset)/ba:0;}
bool SeekFrame(Decoder&x,u64 f){if(!x.open||f>x.info.totalFrames)return false;if(x.info.codec==Codec::Flac){if(f==x.framePos)return true;if(f==0){x.pos=x.info.dataOffset;x.framePos=0;x.flacIndex=x.flacCount=0;return true;}return false;}u32 ba=x.info.channels*(x.info.bitsPerSample/8);u64 p=(u64)x.info.dataOffset+f*ba;if(p>x.bytes)return false;x.pos=(u32)p;return true;}
static i16 pcm(const u8*p,u16 bits){if(bits==8)return (i16)(((i32)p[0]-128)<<8);if(bits==16)return (i16)le16(p);if(bits==24){i32 v=(i32)((u32)p[0]|((u32)p[1]<<8)|((u32)p[2]<<16));if(v&0x800000)v|=(i32)0xff000000;return (i16)(v>>8);}return (i16)((i32)le32(p)>>16);}
static i16 flac16(i32 v,u16 bits){if(bits>16)v>>=(bits-16);else if(bits<16)v<<=(16-bits);if(v>32767)v=32767;if(v<-32768)v=-32768;return (i16)v;}
u32 ReadStereo16(Decoder&x,i16*out,u32 frames){if(!x.open||!out)return 0;if(x.info.codec==Codec::WavPcm){u32 sb=x.info.bitsPerSample/8,ba=x.info.channels*sb,end=x.info.dataOffset+x.info.dataBytes,n=0;while(n<frames&&x.pos+ba<=end){i16 l=pcm(x.data+x.pos,x.info.bitsPerSample),r=x.info.channels==2?pcm(x.data+x.pos+sb,x.info.bitsPerSample):l;out[n*2]=l;out[n*2+1]=r;x.pos+=ba;n++;}return n;}if(x.info.codec==Codec::Flac){u32 n=0;while(n<frames){if(x.flacIndex>=x.flacCount){if(!decodeFlacFrame(x))break;}u32 i=x.flacIndex++;out[n*2]=flac16(x.flacPcm[i*2],x.info.bitsPerSample);out[n*2+1]=flac16(x.flacPcm[i*2+1],x.info.bitsPerSample);x.framePos++;n++;}return n;}return 0;}
}
