#include "BrowserResourceTransport.hpp"
#include "BrowserSession.hpp"
#include "BrowserStyle.hpp"
#include "BrowserImage.hpp"
#include "Dns.hpp"
#include "Arp.hpp"
#include "E1000.hpp"
#include "NetworkCore.hpp"
namespace Davis::BrowserResourceTransport {
State state{};
static Net::Ipv4 hopFor(Net::Ipv4 dst){for(u32 i=0;i<4;i++)if((dst.b[i]&Net::state.config.netmask.b[i])!=(Net::state.config.address.b[i]&Net::state.config.netmask.b[i]))return Net::state.config.gateway;return dst;}
static void fail(){if(state.index<BrowserResources::state.count)BrowserResources::state.items[state.index].phase=BrowserResources::Phase::Failed;if(state.socket){Tcp::Release(*state.socket);state.socket=nullptr;}state.phase=Phase::Idle;state.failed++;}
static bool begin(){for(u32 i=0;i<BrowserResources::state.count;i++){auto&r=BrowserResources::state.items[i];if(!r.valid||r.phase!=BrowserResources::Phase::Queued)continue;state.index=i;state.response={};state.socket=nullptr;state.bodyBytes=0;state.dnsQueryNeeded=false;state.arpNeeded=false;if(!Browser::ParseUrl(r.url,state.url)||state.url.https){r.phase=BrowserResources::Phase::Unsupported;continue;}state.requestBytes=Browser::BuildHttpGet(state.url,state.request,sizeof(state.request));if(!state.requestBytes){r.phase=BrowserResources::Phase::Failed;continue;}Dns::state.resolved=false;Dns::state.waiting=false;state.dnsQueryNeeded=true;state.phase=Phase::Resolving;state.started++;return true;}return false;}
void Init(){state={};BrowserImage::Init();}
void Pump(){if(!Net::state.config.configured)return;if(state.phase==Phase::Idle){begin();return;}if(state.phase==Phase::Resolving){if(Dns::state.retryNeeded){Dns::state.retryNeeded=false;state.dnsQueryNeeded=true;}Net::Mac gw{};if(state.dnsQueryNeeded&&!Dns::state.waiting&&Arp::Lookup(Net::state.config.gateway,gw)){Net::Packet q{};if(Dns::BuildQuery(state.url.host,gw,q)&&E1000::Send(q.data,q.bytes)){Net::state.txPackets++;state.dnsQueryNeeded=false;}}if(Dns::state.resolved){state.address=Dns::state.answer;state.nextHopIp=hopFor(state.address);if(Arp::Lookup(state.nextHopIp,state.nextHop)){state.socket=Tcp::Open(state.address,state.nextHop,state.url.port);if(!state.socket){fail();return;}state.phase=Phase::Connecting;}else state.arpNeeded=true;}if(state.arpNeeded){Net::Packet a{};if(Arp::Request(state.nextHopIp,a)&&E1000::Send(a.data,a.bytes)){Net::state.txPackets++;state.arpNeeded=false;}}return;}if(!state.socket||state.socket->phase==Tcp::Phase::Failed){fail();return;}Net::Packet p{};if(state.phase==Phase::Connecting){if(state.socket->phase==Tcp::Phase::SynSent){if(Tcp::BuildPending(*state.socket,p)&&E1000::Send(p.data,p.bytes))Net::state.txPackets++;return;}if(state.socket->phase==Tcp::Phase::Established)state.phase=Phase::Sending;}if(state.phase==Phase::Sending){if(Tcp::SendData(*state.socket,state.request,state.requestBytes,p)&&E1000::Send(p.data,p.bytes)){Net::state.txPackets++;state.phase=Phase::Receiving;}return;}if(state.phase!=Phase::Receiving)return;if(Tcp::BuildPending(*state.socket,p)&&E1000::Send(p.data,p.bytes))Net::state.txPackets++;if(!state.socket->peerClosed)return;if(!Browser::ParseHttpResponse((const char*)state.socket->receive,state.socket->receiveBytes,state.response)||state.response.status<200||state.response.status>=300){fail();return;}const char*src=(const char*)state.socket->receive+state.response.headerBytes;u32 n=state.response.bodyBytes;if(state.response.chunked){bool done=false;u32 out=0;if(!Browser::DecodeChunked(src,n,state.body,sizeof(state.body),out,done)||!done){fail();return;}n=out;}else{if(state.response.hasContentLength&&n>state.response.contentLength)n=state.response.contentLength;if(n>sizeof(state.body))n=sizeof(state.body);for(u32 i=0;i<n;i++)state.body[i]=src[i];}state.bodyBytes=n;auto&r=BrowserResources::state.items[state.index];r.bytes=n;r.phase=BrowserResources::Phase::Ready;if(r.kind==BrowserResources::Kind::Stylesheet){BrowserStyle::ParseStylesheet(state.body,n);state.cssApplied++;}else {BrowserImage::Store(r.url,(const u8*)state.body,n);state.imagesCached++;}state.completed++;Tcp::Release(*state.socket);state.socket=nullptr;state.phase=Phase::Idle;}
}
