#include "BrowserSession.hpp"
#include "Dns.hpp"
#include "Arp.hpp"
#include "NetworkCore.hpp"
#include "E1000.hpp"
#include "BrowserDocument.hpp"
#include "BrowserResources.hpp"
namespace Davis::BrowserSession {
State state{};
static void copy(char*d,u32 cap,const char*s){u32 i=0;if(!cap)return;while(s&&s[i]&&i+1<cap){d[i]=s[i];i++;}d[i]=0;}
static Net::Ipv4 hopFor(Net::Ipv4 dst){Net::Ipv4 h=dst;u32 same=1;for(u32 i=0;i<4;i++)if((dst.b[i]&Net::state.config.netmask.b[i])!=(Net::state.config.address.b[i]&Net::state.config.netmask.b[i]))same=0;return same?h:Net::state.config.gateway;}
void Init(){state={};BrowserDocument::Init();BrowserResources::Init();state.ready=true;}
bool Start(const char* text){if(!state.ready||!Browser::ParseUrl(text,state.url))return false;if(state.socket){Tcp::Release(*state.socket);state.socket=nullptr;}copy(state.current,MaxUrl,text);state.response={};state.starts++;if(state.url.https){state.phase=Phase::HttpsUnsupported;return false;}state.requestBytes=Browser::BuildHttpGet(state.url,state.request,sizeof(state.request));if(!state.requestBytes){state.phase=Phase::Failed;state.failures++;return false;}state.phase=Phase::Resolving;Dns::state.resolved=false;Dns::state.waiting=false;state.dnsQueryNeeded=true;state.arpNeeded=false;return true;}
bool Navigate(const char*u){state.redirectDepth=0;if(!Start(u))return false;if(state.historyCount==0||state.historyIndex+1>=MaxHistory){if(state.historyCount<MaxHistory)state.historyIndex=state.historyCount++;else{for(u32 i=1;i<MaxHistory;i++)copy(state.history[i-1],MaxUrl,state.history[i]);state.historyIndex=MaxHistory-1;}}else{state.historyIndex++;state.historyCount=state.historyIndex+1;}copy(state.history[state.historyIndex],MaxUrl,u);return true;}
bool Back(){if(!state.historyCount||state.historyIndex==0)return false;state.historyIndex--;state.redirectDepth=0;return Start(state.history[state.historyIndex]);}
bool Forward(){if(state.historyIndex+1>=state.historyCount)return false;state.historyIndex++;state.redirectDepth=0;return Start(state.history[state.historyIndex]);}
bool ResolveLink(const char*h,char*out,u32 cap){return Browser::ResolveUrl(state.url,h,out,cap);}
void Pump(){if(!state.ready||!Net::state.config.configured)return;if(state.phase==Phase::Resolving){if(Dns::state.resolved){state.address=Dns::state.answer;Net::Ipv4 hop=hopFor(state.address);state.nextHopIp=hop;if(Arp::Lookup(hop,state.nextHop)){state.socket=Tcp::Open(state.address,state.nextHop,state.url.port);if(state.socket)state.phase=Phase::Connecting;else{state.phase=Phase::Failed;state.failures++;}}else state.arpNeeded=true;}return;}if(!state.socket)return;if(state.socket->phase==Tcp::Phase::Failed){Tcp::Release(*state.socket);state.socket=nullptr;state.phase=Phase::Failed;state.failures++;return;}Net::Packet p{};if(state.phase==Phase::Connecting){if(state.socket->phase==Tcp::Phase::SynSent){if(Tcp::BuildPending(*state.socket,p)&&E1000::Send(p.data,p.bytes))Net::state.txPackets++;return;}if(state.socket->phase==Tcp::Phase::Established)state.phase=Phase::Sending;}if(state.phase==Phase::Sending){if(Tcp::SendData(*state.socket,state.request,state.requestBytes,p)&&E1000::Send(p.data,p.bytes)){Net::state.txPackets++;state.phase=Phase::Receiving;}return;}if(state.phase==Phase::Receiving){if(Tcp::BuildPending(*state.socket,p)&&E1000::Send(p.data,p.bytes))Net::state.txPackets++;if(state.socket->receiveBytes)Browser::ParseHttpResponse((const char*)state.socket->receive,state.socket->receiveBytes,state.response);if(state.socket->peerClosed){Browser::ParseHttpResponse((const char*)state.socket->receive,state.socket->receiveBytes,state.response);if(!state.response.headerBytes){state.phase=Phase::Failed;state.failures++;return;}if(state.response.status>=300&&state.response.status<400&&state.response.location[0]){if(state.redirectDepth>=MaxRedirects){state.phase=Phase::Failed;state.failures++;return;}char next[MaxUrl];if(!Browser::ResolveUrl(state.url,state.response.location,next,sizeof(next))){state.phase=Phase::Failed;state.failures++;return;}u32 depth=state.redirectDepth+1;state.redirects++;if(Start(next)){state.redirectDepth=depth;copy(state.current,MaxUrl,next);}else{state.phase=Phase::Failed;state.failures++;}return;}const char*body=(const char*)state.socket->receive+state.response.headerBytes;u32 bodyBytes=state.response.bodyBytes;if(state.response.chunked){bool done=false;u32 decoded=0;if(!Browser::DecodeChunked(body,bodyBytes,state.decodedBody,sizeof(state.decodedBody),decoded,done)||!done){state.phase=Phase::Failed;state.failures++;return;}state.decodedBytes=decoded;body=state.decodedBody;bodyBytes=decoded;}else if(state.response.hasContentLength&&bodyBytes>state.response.contentLength)bodyBytes=state.response.contentLength;state.phase=Phase::Complete;BrowserDocument::Parse(body,bodyBytes);BrowserResources::Discover(body,bodyBytes,state.current);state.completes++;Tcp::Release(*state.socket);state.socket=nullptr;}}}
}
