#include "BrowserStyle.hpp"
namespace Davis::BrowserStyle { Sheet sheet{};
static bool ws(char c){return c==' '||c=='\t'||c=='\r'||c=='\n';}
static char lower(char c){return c>='A'&&c<='Z'?c+32:c;}
static bool eq(const char*a,const char*b){u32 i=0;for(;a[i]&&b[i];i++)if(lower(a[i])!=lower(b[i]))return false;return !a[i]&&!b[i];}
static bool starts(const char*a,const char*b){for(u32 i=0;b[i];i++)if(!a[i]||lower(a[i])!=lower(b[i]))return false;return true;}
static u32 hex(char c){if(c>='0'&&c<='9')return c-'0';c=lower(c);return c>='a'&&c<='f'?c-'a'+10:0;}
static bool color(const char*v,u32&out){while(ws(*v))v++;if(*v=='#'){v++;u32 n=0,c=0;while(v[n]&&n<6){char x=v[n];if(!((x>='0'&&x<='9')||(lower(x)>='a'&&lower(x)<='f')))break;c=(c<<4)|hex(x);n++;}if(n==6){out=c;return true;}if(n==3){out=((c>>8)*17<<16)|(((c>>4)&15)*17<<8)|((c&15)*17);return true;}}if(starts(v,"black")){out=0;return true;}if(starts(v,"white")){out=0xFFFFFF;return true;}if(starts(v,"blue")){out=0x0000FF;return true;}if(starts(v,"red")){out=0xFF0000;return true;}if(starts(v,"green")){out=0x008000;return true;}return false;}
static i16 number(const char*v){while(ws(*v))v++;i32 n=0;while(*v>='0'&&*v<='9'){n=n*10+(*v-'0');v++;if(n>4096)return 4096;}return (i16)n;}
static void apply(Style&s,const char*d){u32 p=0;while(d[p]){while(ws(d[p])||d[p]==';')p++;char key[32]{};u32 k=0;while(d[p]&&d[p]!=':'&&k<31)key[k++]=lower(d[p++]);while(k&&ws(key[k-1]))key[--k]=0;if(d[p]==':')p++;char val[64]{};u32 z=0;while(d[p]&&d[p]!=';'&&z<63)val[z++]=d[p++];val[z]=0;u32 c;if(eq(key,"color")&&color(val,c))s.foreground=c;else if(eq(key,"background")||eq(key,"background-color")){if(color(val,c))s.background=c;}else if(eq(key,"border-color")&&color(val,c))s.borderColor=c;else if(eq(key,"margin-top"))s.marginTop=number(val);else if(eq(key,"margin-bottom"))s.marginBottom=number(val);else if(eq(key,"padding-left"))s.paddingLeft=number(val);else if(eq(key,"padding-right"))s.paddingRight=number(val);else if(eq(key,"width"))s.width=number(val);else if(eq(key,"height"))s.height=number(val);else if(eq(key,"border-width"))s.borderWidth=number(val);else if(eq(key,"font-size")){i16 n=number(val);s.scale=n>=24?2:1;}else if(eq(key,"text-decoration")&&starts(val,"underline"))s.underline=true;}}
void Init(){sheet={};}
void ParseStylesheet(const char*c,u32 n){if(!c)return;u32 p=0;while(p<n&&sheet.count<MaxRules){while(p<n&&ws(c[p]))p++;u32 ss=p;while(p<n&&c[p]!='{')p++;if(p>=n)break;u32 se=p++;u32 ds=p;while(p<n&&c[p]!='}')p++;u32 de=p;if(p<n)p++;Rule&r=sheet.rules[sheet.count++];r={};u32 z=0;for(u32 i=ss;i<se&&z+1<MaxSelector;i++)if(!ws(c[i])||z)r.selector[z++]=c[i];while(z&&ws(r.selector[z-1]))r.selector[--z]=0;z=0;for(u32 i=ds;i<de&&z+1<MaxDeclarations;i++)r.declarations[z++]=c[i];r.declarations[z]=0;r.order=(u16)(sheet.count-1);r.specificity=r.selector[0]=='#'?100:(r.selector[0]=='.'?10:1);r.valid=true;}if(p<n)sheet.truncated=true;}
Style ForNode(BrowserDocument::NodeType t){Style s{0x00182030,0x00FFFFFF,0x00A0A0A0,2,6,0,0,0,0,0,1,false};switch(t){case BrowserDocument::NodeType::Heading1:s.scale=2;s.marginTop=10;s.marginBottom=8;break;case BrowserDocument::NodeType::Heading2:s.scale=2;s.marginTop=8;s.marginBottom=6;break;case BrowserDocument::NodeType::Heading3:s.marginTop=8;s.marginBottom=5;break;case BrowserDocument::NodeType::ListItem:s.paddingLeft=16;break;case BrowserDocument::NodeType::Link:s.foreground=0x001B64B2;s.underline=true;break;default:break;}return s;}
static bool containsClass(const char*classes,const char*want){u32 p=0;while(classes[p]){while(classes[p]==' ')p++;u32 q=0;while(classes[p+q]&&classes[p+q]!=' '&&want[q]&&lower(classes[p+q])==lower(want[q]))q++;if(!want[q]&&(classes[p+q]==0||classes[p+q]==' '))return true;while(classes[p]&&classes[p]!=' ')p++;}return false;}
static bool match(const char*s,const BrowserDocument::Node&n){if(!s[0])return false;if(s[0]=='#')return eq(s+1,n.id);if(s[0]=='.')return containsClass(n.klass,s+1);return eq(s,n.tag);}
Style Compute(const BrowserDocument::Node&n){Style s=ForNode(n.type);u16 lastSpec=0,lastOrder=0;bool have=false;for(u32 pass=0;pass<3;pass++)for(u32 i=0;i<sheet.count;i++){auto&r=sheet.rules[i];if(!r.valid||!match(r.selector,n))continue;u32 bucket=r.specificity>=100?2:(r.specificity>=10?1:0);if(bucket!=pass)continue;apply(s,r.declarations);lastSpec=r.specificity;lastOrder=r.order;have=true;}(void)lastSpec;(void)lastOrder;(void)have;if(n.inlineStyle[0])apply(s,n.inlineStyle);return s;}
}
