#include "BrowserCore.hpp"
namespace Davis::Browser {
static bool pref(const char*s,const char*p){while(*p)if(*s++!=*p++)return false;return true;} static char lower(char c){return c>='A'&&c<='Z'?c+32:c;} static bool ieq(char a,char b){return lower(a)==lower(b);}
static bool put(char*out,u32 cap,u32&n,const char*s){while(*s){if(n+1>=cap)return false;out[n++]=*s++;}return true;}
static void copytrim(char*out,u32 cap,const char*d,u32 a,u32 b){while(a<b&&(d[a]==' '||d[a]=='\t'))a++;while(b>a&&(d[b-1]==' '||d[b-1]=='\t'||d[b-1]=='\r'||d[b-1]=='\n'))b--;u32 n=0;while(a<b&&n+1<cap)out[n++]=d[a++];if(cap)out[n]=0;}
static bool headerName(const char*d,u32 a,u32 colon,const char*n){u32 z=0;while(n[z])z++;if(colon-a!=z)return false;for(u32 i=0;i<z;i++)if(!ieq(d[a+i],n[i]))return false;return true;}
bool ParseUrl(const char*t,Url&o){o={};if(!t)return false;const char*p=t;if(pref(p,"https://")){o.https=true;o.port=443;p+=8;}else if(pref(p,"http://")){o.port=80;p+=7;}else{o.port=80;}u32 h=0;while(*p&&*p!='/'&&*p!=':'&&h+1<MaxHost)o.host[h++]=*p++;if(!h)return false;if(*p==':'){p++;u32 port=0;while(*p>='0'&&*p<='9'){port=port*10+(*p++-'0');if(port>65535)return false;}if(!port)return false;o.port=(u16)port;}u32 q=0;if(*p!='/')o.path[q++]='/';while(*p&&q+1<MaxPath)o.path[q++]=*p++;o.valid=true;return true;}
u32 BuildHttpGet(const Url&u,char*out,u32 cap){if(!u.valid||!out||cap<32)return 0;u32 n=0;if(!put(out,cap,n,"GET ")||!put(out,cap,n,u.path)||!put(out,cap,n," HTTP/1.1\r\nHost: ")||!put(out,cap,n,u.host)||!put(out,cap,n,"\r\nUser-Agent: DavisBrowser/0.2\r\nConnection: close\r\nAccept: text/html,text/plain,*/*\r\nAccept-Encoding: identity\r\n\r\n"))return 0;out[n]=0;return n;}
bool ParseHttpResponse(const char*d,u32 n,HttpResponse&o){o={};if(!d||n<12||!pref(d,"HTTP/1."))return false;u32 i=0;while(i<n&&d[i]!=' ')i++;while(i<n&&d[i]==' ')i++;u32 s=0,c=0;while(i<n&&d[i]>='0'&&d[i]<='9'&&c<3){s=s*10+(d[i++]-'0');c++;}if(c!=3)return false;o.status=(u16)s;u32 end=0;for(i=0;i+3<n;i++)if(d[i]=='\r'&&d[i+1]=='\n'&&d[i+2]=='\r'&&d[i+3]=='\n'){end=i+4;break;}if(!end)return true;o.headerBytes=end;o.bodyBytes=n-end;u32 line=0;while(line+1<end&&!(d[line]=='\r'&&d[line+1]=='\n'))line++;line+=2;while(line+2<end){u32 e=line;while(e+1<end&&!(d[e]=='\r'&&d[e+1]=='\n'))e++;if(e==line)break;u32 colon=line;while(colon<e&&d[colon]!=':')colon++;if(colon<e){u32 v=colon+1;if(headerName(d,line,colon,"Content-Length")){while(v<e&&(d[v]==' '||d[v]=='\t'))v++;u32 x=0;bool any=false;while(v<e&&d[v]>='0'&&d[v]<='9'){any=true;x=x*10+(d[v++]-'0');}if(any){o.contentLength=x;o.hasContentLength=true;}}else if(headerName(d,line,colon,"Transfer-Encoding")){for(u32 p=v;p+6<e;p++)if(ieq(d[p],'c')&&ieq(d[p+1],'h')&&ieq(d[p+2],'u')&&ieq(d[p+3],'n')&&ieq(d[p+4],'k')&&ieq(d[p+5],'e')&&ieq(d[p+6],'d'))o.chunked=true;}else if(headerName(d,line,colon,"Location"))copytrim(o.location,MaxLocation,d,v,e);else if(headerName(d,line,colon,"Content-Type"))copytrim(o.contentType,MaxContentType,d,v,e);else if(headerName(d,line,colon,"Connection")){for(u32 p=v;p+4<e;p++)if(ieq(d[p],'c')&&ieq(d[p+1],'l')&&ieq(d[p+2],'o')&&ieq(d[p+3],'s')&&ieq(d[p+4],'e'))o.connectionClose=true;}}line=e+2;}
o.complete=o.hasContentLength?o.bodyBytes>=o.contentLength:false;return true;}
static int hex(char c){if(c>='0'&&c<='9')return c-'0';c=lower(c);if(c>='a'&&c<='f')return c-'a'+10;return -1;}
bool DecodeChunked(const char*in,u32 n,char*out,u32 cap,u32&used,bool&done){used=0;done=false;u32 p=0;while(p<n){u32 size=0;bool any=false;while(p<n&&in[p]!='\r'){int h=hex(in[p]);if(h<0){if(in[p]==';'){while(p<n&&in[p]!='\r')p++;break;}return false;}any=true;if(size>0x0FFFFFFF)return false;size=(size<<4)|(u32)h;p++;}if(!any||p+1>=n||in[p]!='\r'||in[p+1]!='\n')return false;p+=2;if(size==0){done=true;return true;}if(p+size+2>n)return true;if(used+size>cap)return false;for(u32 i=0;i<size;i++)out[used++]=in[p+i];p+=size;if(p+1>=n||in[p]!='\r'||in[p+1]!='\n')return false;p+=2;}return true;}
bool ResolveUrl(const Url&b,const char*r,char*out,u32 cap){if(!r||!r[0]||!out||cap<8)return false;if(pref(r,"http://")||pref(r,"https://")){u32 n=0;return put(out,cap,n,r)?(out[n]=0,true):false;}u32 n=0;if(!put(out,cap,n,b.https?"https://":"http://")||!put(out,cap,n,b.host))return false;if((b.https&&b.port!=443)||(!b.https&&b.port!=80)){if(n+7>=cap)return false;out[n++]=':';char t[6];u32 z=0,x=b.port;do{t[z++]=(char)('0'+x%10);x/=10;}while(x&&z<6);while(z)out[n++]=t[--z];}if(r[0]=='/'){if(!put(out,cap,n,r))return false;}else{const char*path=b.path;u32 last=0;for(u32 i=0;path[i];i++)if(path[i]=='/')last=i;for(u32 i=0;i<=last;i++){if(n+1>=cap)return false;out[n++]=path[i];}if(!put(out,cap,n,r))return false;}out[n]=0;return true;}
}
