#include "Dns.hpp"
namespace Davis::Dns {State state{};static void w16(u8*p,u16 v){p[0]=v>>8;p[1]=v;}static u16 r16(const u8*p){return (u16)((u16)p[0]<<8|p[1]);}
void Init(){state={};state.nextId=0xD500;} bool BuildQuery(const char*name,Net::Mac dm,Net::Packet&o){if(!name||!Net::state.config.configured)return false;u8 q[256]{};u16 id=++state.nextId;w16(q,id);w16(q+2,0x0100);w16(q+4,1);u32 k=12,lab=k++;for(u32 i=0;name[i];i++){if(k+5>=sizeof(q))return false;if(name[i]=='.'){q[lab]=(u8)(k-lab-1);lab=k++;}else q[k++]=(u8)name[i];}q[lab]=(u8)(k-lab-1);q[k++]=0;w16(q+k,1);k+=2;w16(q+k,1);k+=2;state.pendingId=id;u32 i=0;for(;name[i]&&i<95;i++)state.pending[i]=name[i];state.pending[i]=0;state.waiting=true;state.resolved=false;state.retryNeeded=false;state.waitTicks=0;state.queries++;return Net::BuildIpv4Udp(o,Net::state.config.mac,dm,Net::state.config.address,Net::state.config.dns,Net::state.nextEphemeral++,53,q,k);}
static bool skip(const u8*p,u32 n,u32&k){u32 guard=0;while(k<n&&guard++<128){u8 c=p[k++];if(!c)return true;if((c&0xC0)==0xC0){if(k>=n)return false;k++;return true;}if(k+c>n)return false;k+=c;}return false;}
void OnFrame(const u8*f,u32 n){Net::Ipv4 s{},d{};u16 sp=0,dp=0;const u8*p=nullptr;u32 pn=0;if(!state.waiting||!Net::ParseIpv4Udp(f,n,s,d,sp,dp,p,pn)||sp!=53||pn<12||r16(p)!=state.pendingId)return;
 // Only accept replies from the configured resolver, with QR set and no DNS error.
 for(u32 i=0;i<4;i++)if(s.b[i]!=Net::state.config.dns.b[i])return;u16 flags=r16(p+2);if((flags&0x8000)==0||(flags&0x000f)!=0)return;u16 qd=r16(p+4),an=r16(p+6);u32 k=12;for(u32 i=0;i<qd;i++){if(!skip(p,pn,k)||k+4>pn)return;k+=4;}for(u32 i=0;i<an;i++){if(!skip(p,pn,k)||k+10>pn)return;u16 type=r16(p+k),klass=r16(p+k+2),len=r16(p+k+8);k+=10;if(k+len>pn)return;if(type==1&&klass==1&&len==4){for(u32 j=0;j<4;j++)state.answer.b[j]=p[k+j];state.resolved=true;state.waiting=false;state.retryNeeded=false;state.retries=0;state.responses++;return;}k+=len;}}
void Tick(){if(!state.waiting)return;if(++state.waitTicks>=500){state.waitTicks=0;state.waiting=false;state.timeouts++;if(state.retries<4){state.retries++;state.retryNeeded=true;}else state.retryNeeded=false;}}
}
