#include "DriverSelection.hpp"
namespace Davis::DriverSelection {
State state{};
static DriverCatalog::Family familyOf(const Pci::Device&d,bool&ok){ok=true;if(d.classCode==0x0c&&d.subclass==0x03)return DriverCatalog::Family::Usb;if(d.classCode==0x01)return DriverCatalog::Family::Storage;if(d.classCode==0x04&&d.subclass==0x03)return DriverCatalog::Family::Audio;if(d.classCode==0x02&&d.subclass==0x00)return DriverCatalog::Family::Ethernet;if(d.classCode==0x02&&d.subclass==0x80)return DriverCatalog::Family::Wifi;if(d.classCode==0x03)return DriverCatalog::Family::Graphics;ok=false;return DriverCatalog::Family::Input;}
void Init(){state={};state.ready=true;}
static void insert(Binding&b,const DriverCatalog::Match*m){if(!m)return;u32 pos=0;while(pos<b.candidateCount&&b.candidates[pos].score>=m->score)pos++;if(pos>=MaxCandidates)return;u32 end=b.candidateCount<MaxCandidates?b.candidateCount:MaxCandidates-1;for(u32 i=end;i>pos;i--)b.candidates[i]=b.candidates[i-1];b.candidates[pos]={m,m->score,false};if(b.candidateCount<MaxCandidates)b.candidateCount++;}
void Discover(){if(!state.ready)Init();state.count=0;Pci::State p{};Pci::Scan(p);u32 catalogCount=0;const auto*table=DriverCatalog::Table(catalogCount);for(u32 i=0;i<p.count&&state.count<MaxBindings;i++){bool ok=false;auto fam=familyOf(p.devices[i],ok);if(!ok)continue;Binding b{};b.pci=p.devices[i];b.family=fam;b.active=true;for(u32 j=0;j<catalogCount;j++){const auto&m=table[j];if(m.bus!=DriverCatalog::Bus::Pci||m.family!=fam)continue;if(m.vendor&&m.vendor!=b.pci.vendor)continue;if(m.device&&m.device!=b.pci.device)continue;if(m.baseClass&&m.baseClass!=b.pci.classCode)continue;if(m.subClass&&m.subClass!=b.pci.subclass)continue;if(m.progIf&&m.progIf!=b.pci.progIf)continue;insert(b,&m);}if(b.candidateCount)state.bindings[state.count++]=b;}}
const Candidate* Selected(const Binding&b){if(!b.active||b.selected>=b.candidateCount)return nullptr;return &b.candidates[b.selected];}
bool FailSelected(u32 n){if(n>=state.count)return false;auto&b=state.bindings[n];if(b.selected<b.candidateCount)b.candidates[b.selected].failed=true;while(++b.selected<b.candidateCount)if(!b.candidates[b.selected].failed)return true;b.active=false;return false;}
}
