#include "E1000.hpp"
namespace Davis::E1000 {
State state{};
static volatile u32* R(u32 off){return (volatile u32*)(uptr)(state.mmio+off);} static u32 rd(u32 o){return *R(o);} static void wr(u32 o,u32 v){*R(o)=v;}
bool IsSupported(const Pci::Device&d){if(d.vendor!=0x8086)return false;switch(d.device){case 0x100E:case 0x100F:case 0x10D3:case 0x1502:case 0x153A:case 0x15B8:return true;default:return false;}}
bool Init(const Pci::State&p,Memory::PageAllocator&a){state={};for(u32 i=0;i<p.count;i++)if(IsSupported(p.devices[i])){state.pci=p.devices[i];state.found=true;break;}if(!state.found)return false;u32 bar=state.pci.bar0;if(bar&1)return false;state.mmio=Pci::MemoryBarAddress(state.pci,0);if(!state.mmio)return false;Pci::EnableMemoryBusMaster(state.pci);wr(0x0000,rd(0x0000)|(1u<<6));
 state.txRing=Memory::AllocDma(a,sizeof(TxDesc)*RingCount,4096);state.rxRing=Memory::AllocDma(a,sizeof(RxDesc)*RingCount,4096);state.txBuffers=Memory::AllocDma(a,2048*RingCount,4096);state.rxBuffers=Memory::AllocDma(a,2048*RingCount,4096);if(!state.txRing.virtualAddress||!state.rxRing.virtualAddress||!state.txBuffers.virtualAddress||!state.rxBuffers.virtualAddress){if(state.txRing.physical)Memory::FreeDma(a,state.txRing);if(state.rxRing.physical)Memory::FreeDma(a,state.rxRing);if(state.txBuffers.physical)Memory::FreeDma(a,state.txBuffers);if(state.rxBuffers.physical)Memory::FreeDma(a,state.rxBuffers);state.ready=false;return false;}
 u32 ral=rd(0x5400),rah=rd(0x5404);if(!(rah&(1u<<31))){Memory::FreeDma(a,state.txRing);Memory::FreeDma(a,state.rxRing);Memory::FreeDma(a,state.txBuffers);Memory::FreeDma(a,state.rxBuffers);state.ready=false;return false;}for(u32 i=0;i<4;i++)state.mac.b[i]=(u8)(ral>>(8*i));state.mac.b[4]=(u8)rah;state.mac.b[5]=(u8)(rah>>8);
 auto*tx=(TxDesc*)state.txRing.virtualAddress;auto*rx=(RxDesc*)state.rxRing.virtualAddress;for(u32 i=0;i<RingCount;i++){tx[i]={};tx[i].status=1;rx[i]={};rx[i].address=state.rxBuffers.physical+(u64)i*2048;}
 wr(0x3800,(u32)state.txRing.physical);wr(0x3804,(u32)(state.txRing.physical>>32));wr(0x3808,sizeof(TxDesc)*RingCount);wr(0x3810,0);wr(0x3818,0);wr(0x0400,(1u<<1)|(1u<<3)|(15u<<4)|(64u<<12));
 wr(0x2800,(u32)state.rxRing.physical);wr(0x2804,(u32)(state.rxRing.physical>>32));wr(0x2808,sizeof(RxDesc)*RingCount);wr(0x2810,0);wr(0x2818,RingCount-1);wr(0x0100,(1u<<1)|(1u<<15)|(1u<<26));state.rxNext=0;state.txTail=0;state.link=(rd(0x0008)&2)!=0;state.ready=true;return true;}
bool Send(const void*f,u32 n){if(!state.ready||!f||n==0||n>1518){state.txDrops++;return false;}auto*d=(TxDesc*)state.txRing.virtualAddress;u32 i=state.txTail;if(!(d[i].status&1)){state.txDrops++;return false;}u8*dst=(u8*)state.txBuffers.virtualAddress+i*2048;for(u32 j=0;j<n;j++)dst[j]=((const u8*)f)[j];d[i].address=state.txBuffers.physical+(u64)i*2048;d[i].length=(u16)n;d[i].cmd=(1u<<0)|(1u<<1)|(1u<<3);d[i].status=0;state.txTail=(i+1)%RingCount;wr(0x3818,state.txTail);state.tx++;return true;}
bool Receive(Net::Packet&o){if(!state.ready)return false;auto*d=(RxDesc*)state.rxRing.virtualAddress;u32 i=state.rxNext;if(!(d[i].status&1))return false;u32 n=d[i].length;if(n>Net::MaxFrame){state.rxDrops++;n=0;}o.bytes=n;u8*src=(u8*)state.rxBuffers.virtualAddress+i*2048;for(u32 j=0;j<n;j++)o.data[j]=src[j];d[i].status=0;wr(0x2818,i);state.rxNext=(i+1)%RingCount;if(n)state.rx++;return n!=0;}
}
