#include "HardwareProbe.hpp"
#include "../Arch/x86_64/Cpu.hpp"
#include "PlatformProfile.hpp"
#include "AcpiTables.hpp"
#include "AcpiMadt.hpp"
namespace Davis::HardwareProbe {
State state{};
static void text(const char*s,u32 c=0x00EBF0F6){if(!state.enabled)return;Graphics::Text(state.screen,24,58+(i64)state.row*18,s,c,1);state.row++;}
static char hx(u8 v){return v<10?'0'+v:'A'+v-10;} static void hex8(char*out,u8 v){out[0]=hx(v>>4);out[1]=hx(v&15);} static void hex16(char*out,u16 v){out[0]=hx((v>>12)&15);out[1]=hx((v>>8)&15);out[2]=hx((v>>4)&15);out[3]=hx(v&15);} static void hex32(char*out,u32 v){for(int i=0;i<8;i++)out[i]=hx((v>>(28-i*4))&15);}
static void dec(char*out,u32 v){char t[12];u32 n=0;if(!v){*out++='0';*out=0;return;}while(v){t[n++]=(char)('0'+v%10);v/=10;}while(n)*out++=t[--n];*out=0;}
static void cpuid(u32 leaf,u32 sub,u32&a,u32&b,u32&c,u32&d){asm volatile("cpuid":"=a"(a),"=b"(b),"=c"(c),"=d"(d):"a"(leaf),"c"(sub));}
static void deviceLine(const char*tag,const Pci::Device&x){char l[72]="            00:00.0 0000:0000 00/00/00";u32 n=0;while(tag[n]&&n<10){l[n]=tag[n];n++;}hex8(l+12,x.bus);hex8(l+15,x.slot);l[18]=hx(x.function);hex16(l+20,x.vendor);hex16(l+25,x.device);hex8(l+30,x.classCode);hex8(l+33,x.subclass);hex8(l+36,x.progIf);text(l);}
static void pciDetail(const char*tag,const Pci::Device&x){char l[96]="          BDF 00:00.0 CMD:0000 BAR0:00000000 BAR1:00000000";u32 n=0;while(tag[n]&&n<8){l[n]=tag[n];n++;}hex8(l+14,x.bus);hex8(l+17,x.slot);l[20]=hx(x.function);u32 cs=Pci::ReadConfig(x.bus,x.slot,x.function,0x04);hex16(l+26,(u16)cs);hex32(l+35,Pci::ReadConfig(x.bus,x.slot,x.function,0x10));hex32(l+49,Pci::ReadConfig(x.bus,x.slot,x.function,0x14));text(l);}
static u32 matchingBdfCount(const Pci::Device&x,Pci::Device&first){u32 n=0;for(u32 i=0;i<state.pci.count;i++){const auto&d=state.pci.devices[i];if(d.vendor==x.vendor&&d.device==x.device&&d.classCode==x.classCode&&d.subclass==x.subclass){if(!n)first=d;n++;}}return n;}
static bool duplicateEnabledApic(const AcpiMadt::State&m,u32&a,u32&b){for(u32 i=0;i<m.cpuCount;i++)if(m.cpus[i].enabled)for(u32 j=i+1;j<m.cpuCount;j++)if(m.cpus[j].enabled&&m.cpus[i].apicId==m.cpus[j].apicId){a=i;b=j;return true;}return false;}
void Begin(const BootInfo&b){state={};if(!b.hardwareProbeRequested||!b.framebuffer.base)return;state.enabled=true;state.screen={b.framebuffer};Graphics::Clear(state.screen,Graphics::RGB(10,16,24));Graphics::Text(state.screen,24,18,"DAVIS OS PHYSICAL HARDWARE PROBE v1.30",Graphics::RGB(120,210,255),2);Graphics::Text(state.screen,24,44,"Read-only inventory; storage activation/writes suppressed",Graphics::RGB(190,200,215),1);}
void ScanAndDisplay(const BootInfo&b){if(!state.enabled)return;
 u32 a=0,bx=0,c=0,d=0;cpuid(0,0,a,bx,c,d);u32 maxLeaf=a;char vendor[13];*((u32*)vendor)=bx;*((u32*)(vendor+4))=d;*((u32*)(vendor+8))=c;vendor[12]=0;char cpu[64]="CPU vendor: ";u32 p=12;for(u32 i=0;i<12;i++)cpu[p++]=vendor[i];cpu[p]=0;text(cpu,Graphics::RGB(120,210,255));
 cpuid(1,0,a,bx,c,d);char fam[64]="CPU signature: 0x00000000 APIC:Y x2APIC:Y";hex32(fam+17,a);fam[31]=(d&(1u<<9))?'Y':'N';fam[39]=(c&(1u<<21))?'Y':'N';text(fam);
 char fb[80]="GOP: ";dec(fb+5,b.framebuffer.width);u32 q=5;while(fb[q])q++;fb[q++]='x';dec(fb+q,b.framebuffer.height);while(fb[q])q++;const char*ps=" pitch ";for(u32 i=0;ps[i];i++)fb[q++]=ps[i];dec(fb+q,b.framebuffer.pixelsPerScanLine);text(fb);
 text(b.rsdp?"[PASS] ACPI RSDP supplied":"[NOTE] ACPI RSDP unavailable",b.rsdp?Graphics::RGB(90,235,130):Graphics::RGB(255,205,90)); Acpi::State ac{};Acpi::Discover(b,ac);text(ac.rsdpValid?"[PASS] ACPI checksums/root validated":"[NOTE] ACPI root validation unavailable",ac.rsdpValid?Graphics::RGB(90,235,130):Graphics::RGB(255,205,90));
 AcpiMadt::State madt{};bool madtOk=AcpiMadt::Parse(ac,madt);if(madtOk){char m[80]="[FOUND] MADT CPUs: 00 enabled: 00 IOAPIC: 00 LAPIC:0x00000000";dec(m+19,madt.cpuCount);u32 z=19;while(m[z])z++;const char*e=" enabled: ";for(u32 i=0;e[i];i++)m[z++]=e[i];dec(m+z,madt.enabledCpuCount);while(m[z])z++;const char*io=" IOAPIC: ";for(u32 i=0;io[i];i++)m[z++]=io[i];dec(m+z,madt.ioApicCount);while(m[z])z++;const char*la=" LAPIC:0x";for(u32 i=0;la[i];i++)m[z++]=la[i];hex32(m+z,madt.localApicAddress);m[z+8]=0;text(m,Graphics::RGB(90,235,130));
  char ids[90]="  APIC IDs:";u32 k=11;for(u32 i=0;i<madt.cpuCount&&i<12;i++){ids[k++]=' ';u32 id=madt.cpus[i].apicId;if(id<=0xff){hex8(ids+k,(u8)id);k+=2;}else{hex32(ids+k,id);k+=8;}}ids[k]=0;text(ids);
  u32 da=0,db=0;if(duplicateEnabledApic(madt,da,db)){char w[72]="[WARN] duplicate enabled APIC ID: 00000000 entries 00/00";hex32(w+34,madt.cpus[da].apicId);hex8(w+51,(u8)da);hex8(w+54,(u8)db);text(w,Graphics::RGB(255,120,90));}else text("[PASS] enabled APIC IDs unique",Graphics::RGB(90,235,130));
 }else text("[----] MADT CPU topology unavailable",Graphics::RGB(255,205,90));
 Pci::Scan(state.pci);char pc[64]="PCI functions: 000 storage-class: 000";dec(pc+15,state.pci.count);q=15;while(pc[q])q++;const char*sc=" storage-class: ";for(u32 i=0;sc[i];i++)pc[q++]=sc[i];dec(pc+q,state.pci.storageControllerCount);text(pc,Graphics::RGB(255,205,90));
 // Print every mass-storage function first so a physical photo cannot hide it below the generic inventory cutoff.
 for(u32 i=0;i<state.pci.count;i++)if(state.pci.devices[i].classCode==0x01){deviceLine("STORAGE",state.pci.devices[i]);pciDetail("STORRAW",state.pci.devices[i]);}
 if(state.pci.intelVmdCandidateFound)deviceLine("VMD?",state.pci.intelVmdCandidate);
 if(state.pci.networkFound){deviceLine("NETWORK",state.pci.network);pciDetail("NETRAW",state.pci.network);Pci::Device vf{};u32 vc=matchingBdfCount(state.pci.network,vf);char v[72]="NET VERIFY matches: 000 first 00:00.0";dec(v+20,vc);u32 vi=20;while(v[vi])vi++;const char*ff=" first ";for(u32 i=0;ff[i];i++)v[vi++]=ff[i];hex8(v+vi,vf.bus);vi+=2;v[vi++]=':';hex8(v+vi,vf.slot);vi+=2;v[vi++]='.';v[vi++]=hx(vf.function);v[vi]=0;text(v,vc==1?Graphics::RGB(90,235,130):Graphics::RGB(255,205,90));} if(state.pci.xhciFound){deviceLine("XHCI",state.pci.xhci);pciDetail("XHCIRAW",state.pci.xhci);} if(state.pci.hdaFound)deviceLine("AUDIO",state.pci.hda); if(state.pci.displayFound)deviceLine("DISPLAY",state.pci.display);
 PlatformProfile::State pf{};PlatformProfile::Detect(state.pci,pf);text(pf.hybridGraphics?"[FOUND] hybrid graphics; GOP retained":"[INFO] single/undetermined graphics topology");text(state.pci.i2cFound?"[FOUND] Serial-I/O candidate; ACPI/I2C-HID preferred":"[----] no PCI Serial-I/O candidate");
 text(state.pci.nvmeFound?"[FOUND] native NVMe controller":"[----] no native NVMe class function");text(state.pci.ahciFound?"[FOUND] native AHCI/SATA controller":"[----] no native AHCI class function");text(state.pci.raidFound?"[FOUND] RAID/storage remapping class function":"[----] no RAID class function");text(state.pci.intelVmdCandidateFound?"[PLAN] Intel storage remapping/VMD candidate: inspect, do not bind":"[INFO] no Intel VMD heuristic match");text(state.pci.networkFound?"[FOUND] PCI network controller":"[----] no PCI network controller");text("[SAFE] read-only probe: no physical storage writes",Graphics::RGB(90,235,130));(void)maxLeaf;}
[[noreturn]] void CompleteAndHalt(){text("[STOP] Photograph this screen; v1.30 inventory complete",Graphics::RGB(255,205,90));Cpu::HaltForever();}
}
