#include "Hda.hpp"
#include "KernelMemory.hpp"
#include "../Arch/x86_64/Io.hpp"
namespace Davis::Hda {
State state{};
static inline volatile u8* B(){return (volatile u8*)(uptr)state.mmio;}
static inline u8 R8(u32 o){return *(volatile u8*)(B()+o);} static inline u16 R16(u32 o){return *(volatile u16*)(B()+o);} static inline u32 R32(u32 o){return *(volatile u32*)(B()+o);}
static inline void W8(u32 o,u8 v){*(volatile u8*)(B()+o)=v;}static inline void W16(u32 o,u16 v){*(volatile u16*)(B()+o)=v;} static inline void W32(u32 o,u32 v){*(volatile u32*)(B()+o)=v;}
static bool Wait32(u32 off,u32 mask,bool set,u32 spins){while(spins--){bool on=(R32(off)&mask)!=0;if(on==set)return true;__asm__ __volatile__("pause");}return false;}
void Init(){state={};state.result=Result::Cold;}
bool Discover(const Pci::State&p){Init();if(!p.hdaFound){state.result=Result::NotFound;return false;}auto&d=p.hda;state.bus=d.bus;state.device=d.slot;state.function=d.function;state.vendorId=d.vendor;state.deviceId=d.device;u32 lo=Pci::ReadConfig(d.bus,d.slot,d.function,0x10);if(lo&1u){state.result=Result::InvalidBar;return false;}u32 type=(lo>>1)&3u;if(type==1u||type==3u){state.result=Result::InvalidBar;return false;}u64 base=(u64)(lo&~0xFull);if(type==2u)base|=((u64)Pci::ReadConfig(d.bus,d.slot,d.function,0x14)<<32);if(!base){state.result=Result::InvalidBar;return false;}state.mmio=base;state.discovered=true;state.result=Result::Discovered;return true;}
bool ResetController(u32 spins){if(!state.discovered||!state.mmio)return false;u32 g=R32(0x08);W32(0x08,g&~1u);if(!Wait32(0x08,1u,false,spins)){state.result=Result::ResetTimeout;return false;}W32(0x08,(R32(0x08)|1u));if(!Wait32(0x08,1u,true,spins)){state.result=Result::ResetTimeout;return false;}state.resets++;state.controllerReady=true;state.codecMask=R16(0x0E)&0x7FFFu;if(!state.codecMask){state.result=Result::NoCodec;return false;}return true;}
bool ImmediateVerb(u8 codec,u8 node,u16 verb,u8 payload,u32&response,u32 spins){response=0;if(!state.controllerReady||codec>14||node>0x7F)return false;constexpr u16 BUSY=1u,VALID=2u;while((R16(0x68)&BUSY)&&spins--){__asm__ __volatile__("pause");}if(!spins){state.verbTimeouts++;state.result=Result::VerbTimeout;return false;}W16(0x68,VALID);u32 cmd=((u32)codec<<28)|((u32)node<<20)|((u32)(verb&0xFFF)<<8)|payload;W32(0x60,cmd);W16(0x68,BUSY);while(spins--){u16 s=R16(0x68);if(!(s&BUSY)&&(s&VALID)){response=R32(0x64);W16(0x68,VALID);state.verbs++;return true;}__asm__ __volatile__("pause");}state.verbTimeouts++;state.result=Result::VerbTimeout;return false;}
static bool GetParameter(u8 c,u8 n,u8 p,u32&r,u32 spins){return state.ringsReady?RingVerb(c,n,0xF00,p,r,spins):ImmediateVerb(c,n,0xF00,p,r,spins);}
bool ProbeCodecs(u32 spins){if(!state.controllerReady)return false;state.codecCount=0;for(u8 c=0;c<15;c++){if(!(state.codecMask&(1u<<c)))continue;CodecInfo ci{};ci.address=c;u32 v=0,rev=0,nodes=0;if(!ImmediateVerb(c,0,0xF00,0x00,v,spins))continue;ImmediateVerb(c,0,0xF00,0x02,rev,spins);ImmediateVerb(c,0,0xF00,0x04,nodes,spins);ci.vendorDevice=v;ci.revision=rev;ci.firstFunctionGroup=(nodes>>16)&0xff;ci.functionGroupCount=nodes&0xff;ci.rootNodeCount=nodes;ci.valid=true;state.codecs[state.codecCount++]=ci;}if(!state.codecCount){state.result=Result::VerbError;return false;}state.result=Result::CodecReady;return true;}
static u16 chooseEntries(u8 cap){if(cap&0x40)return 256;if(cap&0x20)return 16;if(cap&0x10)return 2;return 0;}
bool SetupCommandRings(u32 spins){if(!state.controllerReady||!KernelMemory::ready)return false;W8(0x4C,R8(0x4C)&~2u);W8(0x5C,R8(0x5C)&~2u);while(((R8(0x4C)|R8(0x5C))&2u)&&spins--){__asm__ __volatile__("pause");}if(!spins){state.result=Result::RingSetupFailed;return false;}state.corbEntries=chooseEntries(R8(0x4E));state.rirbEntries=chooseEntries(R8(0x5E));if(!state.corbEntries||!state.rirbEntries){state.result=Result::RingSetupFailed;return false;}state.corb=Memory::AllocDma(KernelMemory::allocator,state.corbEntries*4,128);state.rirb=Memory::AllocDma(KernelMemory::allocator,state.rirbEntries*8,128);if(!state.corb.physical||!state.rirb.physical){state.result=Result::RingAllocFailed;return false;}W32(0x40,(u32)state.corb.physical);W32(0x44,(u32)(state.corb.physical>>32));W32(0x50,(u32)state.rirb.physical);W32(0x54,(u32)(state.rirb.physical>>32));u8 cs=state.corbEntries==256?2:state.corbEntries==16?1:0;u8 rs=state.rirbEntries==256?2:state.rirbEntries==16?1:0;W8(0x4E,(R8(0x4E)&~3u)|cs);W8(0x5E,(R8(0x5E)&~3u)|rs);W16(0x4A,0x8000);W16(0x58,0x8000);state.corbWrite=0;state.rirbRead=0;W16(0x48,0);W16(0x5A,1);W8(0x4C,2);W8(0x5C,2);state.ringsReady=true;state.result=Result::RingReady;return true;}
bool RingCommand(u32 cmd,u32&response,u32 spins){response=0;if(!state.ringsReady)return false;auto*corb=(volatile u32*)state.corb.virtualAddress;auto*rirb=(volatile u64*)state.rirb.virtualAddress;u16 next=(state.corbWrite+1)%state.corbEntries;corb[next]=cmd;__asm__ __volatile__("mfence":::"memory");state.corbWrite=next;W16(0x48,next);state.ringVerbs++;while(spins--){u16 hw=R16(0x58)&0xff;if(hw!=state.rirbRead){state.rirbRead=(state.rirbRead+1)%state.rirbEntries;u64 e=rirb[state.rirbRead];response=(u32)e;state.ringResponses++;return true;}__asm__ __volatile__("pause");}state.verbTimeouts++;state.result=Result::VerbTimeout;return false;}
bool RingVerb(u8 codec,u8 node,u16 verb,u8 payload,u32&response,u32 spins){if(codec>14||node>0x7f)return false;return RingCommand(((u32)codec<<28)|((u32)node<<20)|((u32)(verb&0xfff)<<8)|payload,response,spins);}
static bool Verb16(u8 c,u8 n,u8 verb4,u16 payload,u32&r,u32 spins){return RingCommand(((u32)c<<28)|((u32)n<<20)|((u32)(verb4&0xf)<<16)|payload,r,spins);}
static WidgetInfo* FindWidget(u8 c,u8 n){for(u32 i=0;i<state.widgetCount;i++)if(state.widgets[i].valid&&state.widgets[i].codec==c&&state.widgets[i].node==n)return &state.widgets[i];return nullptr;}
static bool ReadConnections(WidgetInfo&w,u32 spins){u32 len=0;if(!GetParameter(w.codec,w.node,0x0E,len,spins))return false;u32 count=len&0x7f;bool longForm=(len&(1u<<7))!=0;if(count>MaxConnections)count=MaxConnections;w.connectionCount=0;for(u32 i=0;i<count;){u32 r=0;if(!RingVerb(w.codec,w.node,0xF02,(u8)i,r,spins))break;u32 per=longForm?2:4;for(u32 j=0;j<per&&i<count;j++,i++){u16 v=longForm?(u16)(r>>(j*16)):(u8)(r>>(j*8));w.connections[w.connectionCount++]=(u8)(v&0x7f);}}return true;}
bool EnumerateTopology(u32 spins){if(!state.ringsReady)return false;state.widgetCount=state.outputWidgets=state.pinWidgets=state.mixerWidgets=0;for(u32 ci=0;ci<state.codecCount;ci++){auto&c=state.codecs[ci];for(u32 fi=0;fi<c.functionGroupCount;fi++){u8 fg=c.firstFunctionGroup+fi;u32 fgType=0;if(!GetParameter(c.address,fg,0x05,fgType,spins))continue;if((fgType&0xff)!=1)continue;u32 nodes=0;if(!GetParameter(c.address,fg,0x04,nodes,spins))continue;u8 first=(nodes>>16)&0xff,count=nodes&0xff;for(u32 wi=0;wi<count&&state.widgetCount<MaxWidgets;wi++){u8 n=first+wi;u32 caps=0;if(!GetParameter(c.address,n,0x09,caps,spins))continue;WidgetInfo w{};w.codec=c.address;w.node=n;w.capabilities=caps;w.type=(WidgetType)((caps>>20)&0xf);w.valid=true;if(w.type==WidgetType::PinComplex){GetParameter(c.address,n,0x0C,w.pinCaps,spins);RingVerb(c.address,n,0xF1C,0,w.defaultConfig,spins);}ReadConnections(w,spins);state.widgets[state.widgetCount++]=w;if(w.type==WidgetType::AudioOutput)state.outputWidgets++;else if(w.type==WidgetType::PinComplex)state.pinWidgets++;else if(w.type==WidgetType::AudioMixer)state.mixerWidgets++;}}}state.result=Result::TopologyReady;return state.widgetCount!=0;}
static bool FindDacPath(u8 c,u8 node,u8*path,u8&len,u32 depth){if(depth>=8)return false;auto*w=FindWidget(c,node);if(!w)return false;path[depth]=node;if(w->type==WidgetType::AudioOutput){len=(u8)(depth+1);return true;}for(u32 i=0;i<w->connectionCount;i++)if(FindDacPath(c,w->connections[i],path,len,depth+1))return true;return false;}
bool SelectPlaybackRoute(u32 spins){(void)spins;state.route={};/* Prefer internal speaker, then headphones, then line-out. This avoids binding the first enumerated pin, which is often HDMI/dock on laptops. */const u8 preferred[3]={1,2,0};for(u32 pref=0;pref<3;pref++)for(u32 i=0;i<state.widgetCount;i++){auto&w=state.widgets[i];if(!w.valid||w.type!=WidgetType::PinComplex)continue;u8 device=(u8)((w.defaultConfig>>20)&0xf);u8 connectivity=(u8)((w.defaultConfig>>30)&3u);if(device!=preferred[pref]||connectivity==1)continue;u8 path[8]{},len=0;if(FindDacPath(w.codec,w.node,path,len,0)){state.route.codec=w.codec;state.route.pin=w.node;state.route.dac=path[len-1];state.route.pathLength=len;for(u32 j=0;j<len;j++)state.route.path[j]=path[j];state.route.valid=true;state.result=Result::RouteReady;return true;}}
 // Fallback: any output-capable pin with a DAC path (some laptops tag speakers as 'other').
 for(u32 i=0;i<state.widgetCount;i++){auto&w=state.widgets[i];if(!w.valid||w.type!=WidgetType::PinComplex)continue;if(!(w.pinCaps&(1u<<4)))continue;u8 path[8]{},len=0;if(FindDacPath(w.codec,w.node,path,len,0)){state.route.codec=w.codec;state.route.pin=w.node;state.route.dac=path[len-1];state.route.pathLength=len;for(u32 j=0;j<len;j++)state.route.path[j]=path[j];state.route.valid=true;state.result=Result::RouteReady;return true;}}
 return false;}
static u32 StreamBase(){u16 g=R16(0x00);u32 input=(g>>8)&0xf;return 0x80+input*0x20;}
static bool SelectConnection(u8 codec,u8 node,u8 target,u32 spins){
 auto*w=FindWidget(codec,node);if(!w||w->connectionCount<2)return true;
 for(u32 i=0;i<w->connectionCount;i++)if(w->connections[i]==target){u32 r=0;return RingVerb(codec,node,0x701,(u8)i,r,spins);}return false;
}
static void UnmuteWidget(u8 codec,u8 node,u32 caps,u32 spins){
 u32 r=0;
 // AWCAP bit 2 = output amp present, bit 1 = input amp present. Set both channels, gain 0, unmuted.
 if(caps&(1u<<2))Verb16(codec,node,0x3,(u16)(0x8000|0x3000),r,spins);
 if(caps&(1u<<1))Verb16(codec,node,0x3,(u16)(0x4000|0x3000),r,spins);
}
bool ProgramPlaybackRoute(u32 spins){
 if(!state.route.valid)return false;u32 r=0;
 // Path is pin -> ... -> DAC. Select each upstream connection explicitly.
 for(u32 i=0;i+1<state.route.pathLength;i++)if(!SelectConnection(state.route.codec,state.route.path[i],state.route.path[i+1],spins)){state.result=Result::RouteProgramFailed;return false;}
 for(u32 i=0;i<state.route.pathLength;i++){auto*w=FindWidget(state.route.codec,state.route.path[i]);if(!w)continue;RingVerb(state.route.codec,w->node,0x705,0,r,spins);UnmuteWidget(state.route.codec,w->node,w->capabilities,spins);}
 auto*pin=FindWidget(state.route.codec,state.route.pin);if(pin){
   RingVerb(state.route.codec,state.route.pin,0x707,0x40,r,spins); // output enable
   if(pin->pinCaps&(1u<<16))RingVerb(state.route.codec,state.route.pin,0x70C,0x02,r,spins); // EAPD enable when supported
 }
 state.routePrograms++;return true;
}
bool PreparePlayback(u32 spins){if(!state.route.valid||!KernelMemory::ready)return false;u16 g=R16(0x00);u32 outputs=(g>>12)&0xf;if(!outputs)return false;state.outputStreamIndex=0;state.streamOffset=StreamBase();state.streamTag=1;u32 o=state.streamOffset;W8(o,0);for(u32 n=0;n<spins&&R8(o)&2;n++)__asm__ __volatile__("pause");W8(o,R8(o)|1);for(u32 n=0;n<spins&&!(R8(o)&1);n++)__asm__ __volatile__("pause");W8(o,R8(o)&~1u);state.bufferBytes=16384;state.playbackData=Memory::AllocDma(KernelMemory::allocator,state.bufferBytes,4096);state.playbackBdl=Memory::AllocDma(KernelMemory::allocator,4*sizeof(BdlEntry),128);if(!state.playbackData.physical||!state.playbackBdl.physical){state.result=Result::PlaybackAllocFailed;return false;}auto*b=(BdlEntry*)state.playbackBdl.virtualAddress;for(u32 i=0;i<4;i++){b[i].address=state.playbackData.physical+i*4096;b[i].length=4096;b[i].flags=1;}W32(o+0x18,(u32)state.playbackBdl.physical);W32(o+0x1c,(u32)(state.playbackBdl.physical>>32));W32(o+0x08,state.bufferBytes);W16(o+0x0c,3);W16(o+0x12,0x0011);u32 r=0;Verb16(state.route.codec,state.route.dac,0x2,0x0011,r,spins);RingVerb(state.route.codec,state.route.dac,0x706,(u8)(state.streamTag<<4),r,spins);if(!ProgramPlaybackRoute(spins))return false;state.lastDmaPosition=0;state.writeQuarter=0;state.playbackPrepared=true;state.result=Result::PlaybackReady;return true;}
bool StartPlayback(){if(!state.playbackPrepared)return false;u32 o=state.streamOffset;u32 ctl=R32(o);ctl&=0x00ffffffu;ctl|=((u32)state.streamTag<<20);ctl|=2u;W32(o,ctl);state.playbackRunning=true;state.playbackStarts++;state.result=Result::PlaybackRunning;return true;}
void StopPlayback(){if(state.playbackPrepared){u32 o=state.streamOffset;W32(o,R32(o)&~2u);}state.playbackRunning=false;}
u32 PlaybackPosition(){if(!state.playbackPrepared)return 0;u32 p=R32(state.streamOffset+0x04);if(state.bufferBytes)p%=state.bufferBytes;state.lastDmaPosition=p;state.dmaPositionReads++;return p;}
bool SubmitStereo16(const i16*samples,u32 frames){if(!state.playbackPrepared||!samples)return false;constexpr u32 QuarterBytes=4096;u32 max=QuarterBytes/4;if(frames>max)frames=max;u32 playQuarter=PlaybackPosition()/QuarterBytes;u32 q=state.writeQuarter&3u;if(q==playQuarter)q=(q+1)&3u;auto*d=(i16*)((u8*)state.playbackData.virtualAddress+q*QuarterBytes);for(u32 i=0;i<frames*2;i++)d[i]=samples[i];for(u32 i=frames*2;i<QuarterBytes/2;i++)d[i]=0;__asm__ __volatile__("mfence":::"memory");state.writeQuarter=(q+1)&3u;state.playbackRefills++;return true;}
void EnableTestTone(bool enable){state.testToneEnabled=enable;}
void FillTestTone(){if(!state.playbackPrepared||!state.testToneEnabled)return;static i16 tone[256*2];static u32 phase=0;for(u32 i=0;i<256;i++){phase=(phase+1)%96; // 48 kHz / 96 = 500 Hz
 i16 v=phase<48?6000:-6000;tone[i*2]=v;tone[i*2+1]=v;}SubmitStereo16(tone,256);state.testToneFrames+=256;}
bool BringUp(const Pci::State&p){if(!Discover(p))return false;if(!ResetController())return false;if(!ProbeCodecs())return false;if(!SetupCommandRings())return false;if(!EnumerateTopology())return false;if(!SelectPlaybackRoute())return true;PreparePlayback();return true;}
}
