#include "LiveActivation.hpp"
#include "RuntimeCurrent.hpp"
namespace Davis::LiveActivation {
void Init(State&s,u64 ms,u64 mf){s={};s.phase=Phase::Cold;s.maxSwitches=ms;s.maxFaults=mf;}
static MultiAppRuntime::App* firstProof(MultiAppRuntime::State&r){for(usize i=0;i<r.appCount;i++)if(r.apps[i].kind==AppPreemptionA&&r.apps[i].ready)return &r.apps[i];return nullptr;}
bool Verify(State&s,const MultiAppRuntime::State&r,const KernelPlatform::State&p){if(!r.armed||r.result!=MultiAppRuntime::Result::Armed||!r.proof.armed){s.phase=Phase::Failed;s.failure=Failure::RuntimeNotArmed;return false;}if(!KernelPlatform::CanActivate(p)||!p.gdt||!p.preemption){s.phase=Phase::Failed;s.failure=Failure::PlatformNotReady;return false;}const Preemption::Slot*x=Preemption::FindSlot(*p.preemption,r.proof.a.processId);if(!x||!x->valid||!x->cr3||!x->kernelRsp0||!x->sharedKernelMappings){s.phase=Phase::Failed;s.failure=Failure::EndpointInvalid;return false;}s.firstId=x->processId;s.expectedCr3=x->cr3;s.expectedRsp0=x->kernelRsp0;s.phase=Phase::Verified;return true;}
bool Arm(State&s,MultiAppRuntime::State&r,KernelPlatform::State&p){if(s.phase!=Phase::Verified)return false;auto*a=firstProof(r);if(!a||a->loaded.process->id!=s.firstId||a->loaded.space.pml4Physical!=s.expectedCr3||a->kernelRsp0!=s.expectedRsp0){s.phase=Phase::Failed;s.failure=Failure::OwnershipMismatch;return false;}p.preemption->activeCr3=s.expectedCr3;p.preemption->activeKernelRsp0=s.expectedRsp0;p.gdt->tss.rsp0=s.expectedRsp0;p.scheduler->currentId=s.firstId;a->loaded.process->state=Process::State::Running;RuntimeCurrent::Set(a->loaded.process);p.contextSwitch.hardwareEnabled=true;s.phase=Phase::Armed;return true;}
bool ObserveSwitch(State&s){if(s.phase!=Phase::Armed&&s.phase!=Phase::Running)return false;if(++s.switches>s.maxSwitches){s.emergencyCutoff=true;s.phase=Phase::Cutoff;s.failure=Failure::SwitchBudgetExceeded;return false;}s.phase=Phase::Running;return true;}
bool ObserveFault(State&s){if(++s.faults>s.maxFaults){s.emergencyCutoff=true;s.phase=Phase::Cutoff;s.failure=Failure::FaultBudgetExceeded;return false;}return true;}
void Cutoff(State&s,KernelPlatform::State&p){s.emergencyCutoff=true;p.contextSwitch.hardwareEnabled=false;p.liveActivationPermitted=false;if(p.timer)LocalApicTimer::Stop(*p.timer);s.phase=Phase::Cutoff;}
const char* Diagnostic(const State&s,const LiveProof::State&proof){if(s.phase==Phase::Failed)return "LIVE PROOF FAILED";if(s.phase==Phase::Cutoff)return "EMERGENCY PREEMPTION CUTOFF";if(proof.phase==LiveProof::Phase::Passed)return "B FAULTED - KERNEL SURVIVED";if(s.phase==Phase::Running)return "A <-> B SWITCHING";if(s.phase==Phase::Armed)return "A RUNNING";if(s.phase==Phase::Verified)return "LIVE PROOF VERIFIED";return "LIVE PROOF DISARMED";}
}
