#include "LiveDiagnostics.hpp"
#include "PlatformBootstrap.hpp"
#include "LiveTrace.hpp"
#include "LiveRunner.hpp"
namespace Davis::LiveDiagnostics {
static const MultiAppRuntime::App* byKind(const MultiAppRuntime::State&s,u32 k){for(usize i=0;i<s.appCount;i++)if(s.apps[i].kind==k)return &s.apps[i];return nullptr;}
Snapshot Inspect(const MultiAppRuntime::State&s){Snapshot o{};o.appCount=s.appCount;if(s.result==MultiAppRuntime::Result::Disabled){o.gate=Gate::Disabled;return o;}if(!s.armed||s.result!=MultiAppRuntime::Result::Armed){o.gate=Gate::RuntimeMissing;return o;}auto*a=byKind(s,AppPreemptionA);auto*b=byKind(s,AppPreemptionB);if(!a||!b||!a->ready||!b->ready){o.gate=Gate::RuntimeMissing;return o;}o.processA=a->loaded.process?a->loaded.process->id:0;o.processB=b->loaded.process?b->loaded.process->id:0;o.separateCr3=a->loaded.space.pml4Physical&&b->loaded.space.pml4Physical&&a->loaded.space.pml4Physical!=b->loaded.space.pml4Physical;o.separateRsp0=a->kernelRsp0&&b->kernelRsp0&&a->kernelRsp0!=b->kernelRsp0;o.kernelMappings=a->loaded.sharedKernelMappings&&b->loaded.sharedKernelMappings;o.switches=LiveTrace::state.switchCommits;o.faults=LiveTrace::state.userFaults;if(!(o.separateCr3&&o.separateRsp0&&o.kernelMappings)){o.gate=Gate::Failed;return o;} if(LiveTrace::state.kernelReturned&&LiveTrace::state.userFaults&&LiveTrace::state.recoveries)o.gate=Gate::Survived;else if(LiveRunner::state.activation.phase==LiveActivation::Phase::Running||LiveTrace::state.switchCommits)o.gate=Gate::Active;else if(LiveRunner::state.activation.phase==LiveActivation::Phase::Cutoff)o.gate=Gate::Cutoff;else o.gate=PlatformBootstrap::state.ready?Gate::ReadyForActivation:Gate::PlatformBridgePending;return o;}
const char* GateText(Gate g){switch(g){case Gate::Disabled:return "LIVE PROOF DISABLED";case Gate::RuntimeMissing:return "DXE PROOF NOT READY";case Gate::RuntimeReady:return "DXE PROOF READY";case Gate::PlatformBridgePending:return "PLATFORM BRIDGE PENDING";case Gate::ReadyForActivation:return "READY FOR LIVE ACTIVATION";case Gate::Active:return "A <-> B SWITCHING";case Gate::Survived:return "B FAULTED - KERNEL SURVIVED";case Gate::Cutoff:return "EMERGENCY PREEMPTION CUTOFF";default:return "LIVE PROOF FAILED";}}
void DrawPanel(Graphics::Surface&g,i64 x,i64 y,i64 w,const Snapshot&s){u32 bg=0x00101928,edge=0x005B83C5,txt=0x00F1F3F8,mut=0x009AA6BA;Graphics::Rect(g,x,y,w,118,bg);Graphics::Frame(g,x,y,w,118,edge,2);Graphics::Text(g,x+12,y+10,"MULTITASKING PROOF",txt,1);Graphics::Text(g,x+12,y+30,GateText(s.gate),txt,1);Graphics::Text(g,x+12,y+50,s.separateCr3?"CR3 A/B: ISOLATED":"CR3 A/B: NOT VERIFIED",mut,1);Graphics::Text(g,x+12,y+66,s.separateRsp0?"RSP0 A/B: ISOLATED":"RSP0 A/B: NOT VERIFIED",mut,1);Graphics::Text(g,x+12,y+82,s.kernelMappings?"KERNEL MAP: VERIFIED":"KERNEL MAP: NOT VERIFIED",mut,1);Graphics::Text(g,x+12,y+98,s.gate==Gate::ReadyForActivation?"LIVE TIMER: OFF - READY":"LIVE TIMER: OFF (FAIL-CLOSED)",mut,1);}
}
