#include "NvmeControllerTransport.hpp"
namespace Davis::NvmeControllerTransport {
static inline volatile u32*r32(State&s,u32 o){return(volatile u32*)(s.mmio+o);}static inline volatile u64*r64(State&s,u32 o){return(volatile u64*)(s.mmio+o);}
bool DecodeCapabilities(u64 cap,Capabilities&o){o={};o.maxQueueEntries=(u16)((cap&0xffffu)+1u);o.timeoutUnits500ms=(u8)((cap>>24)&0xffu);o.doorbellStrideShift=(u8)((cap>>32)&0x0fu);o.doorbellStrideBytes=4u<<o.doorbellStrideShift;o.nvmCommandSet=((cap>>37)&1u)!=0;o.minPageShift=(u8)(12u+((cap>>48)&0x0fu));o.maxPageShift=(u8)(12u+((cap>>52)&0x0fu));if(!o.maxQueueEntries||!o.nvmCommandSet||o.minPageShift>o.maxPageShift||o.doorbellStrideBytes<4||o.doorbellStrideBytes>32768)return false;o.valid=true;return true;}
bool Bind(State&s,void*m,u32 p){s={};if(!m||p<4096||(p&(p-1)))return false;s.mmio=(volatile u8*)m;s.pageBytes=p;s.cap=*r64(s,0);if(!DecodeCapabilities(s.cap,s.capabilities)){s.stage=Stage::Failed;return false;}u32 sh=0,v=p;while(v>1){v>>=1;sh++;}if(sh<s.capabilities.minPageShift||sh>s.capabilities.maxPageShift){s.stage=Stage::Failed;return false;}s.stage=Stage::Cold;return true;}
bool Disable(State&s,u32 lim){if(!s.mmio||!s.capabilities.valid||lim<1)return false;*r32(s,0x14)&=~1u;__asm__ __volatile__("mfence":::"memory");for(u32 i=0;i<lim;i++){s.polls++;if(!(*r32(s,0x1c)&1u)){s.stage=Stage::Disabled;return true;}}s.stage=Stage::TimedOut;return false;}
bool ConfigureAdmin(State&s,u64 q,u64 c,u16 d){if(s.stage!=Stage::Disabled||d<2||d>s.capabilities.maxQueueEntries||d>4096||!q||!c||(q&(s.pageBytes-1))||(c&(s.pageBytes-1)))return false;*r32(s,0x24)=((u32)(d-1)<<16)|(d-1);*r64(s,0x28)=q;*r64(s,0x30)=c;s.asq=q;s.acq=c;s.adminDepth=d;s.stage=Stage::AdminConfigured;return true;}
bool Enable(State&s,u32 lim){if(s.stage!=Stage::AdminConfigured||lim<1)return false;u32 sh=0;while((1u<<sh)<s.pageBytes)sh++;u32 mps=sh-12;u32 cc=(6u<<16)|(4u<<20)|(mps<<7)|1u;*r32(s,0x14)=cc;__asm__ __volatile__("mfence":::"memory");s.stage=Stage::Enabling;for(u32 i=0;i<lim;i++){s.polls++;u32 c=*r32(s,0x1c);if(c&2u){s.stage=Stage::Failed;return false;}if(c&1u){s.stage=Stage::Ready;return true;}}s.stage=Stage::TimedOut;return false;}
bool ResetAndReconfigure(State&s,u64 q,u64 c,u16 d,u32 lim){s.resets++;if(!Disable(s,lim))return false;if(!ConfigureAdmin(s,q,c,d))return false;return Enable(s,lim);}
}
