#include "Syscall.hpp"
#include "Dxe2.hpp"
#include "DxeServices.hpp"
#include "UserMemory.hpp"
#include "Ipc.hpp"
#include "SystemServices.hpp"
#include "DriverManager.hpp"
#include "Pci.hpp"
#include "DeviceResourceBroker.hpp"
#include "DriverGateway.hpp"
#include "UsbRuntime.hpp"
#include "PciInterrupts.hpp"
#include "IsolationGuard.hpp"
#include "SecurityPolicy.hpp"
#include "UserHeap.hpp"
#include "GraphicsObjectManager.hpp"
#include "MultiAppRuntime.hpp"
#include "BootInfo.hpp"
#include "ForgePersistentStore.hpp"
#include "ForgePackageRegistry.hpp"
namespace Davis::Syscall {
static ObjectHandles::Table gHandles{};
void InitObjectHandles(){ObjectHandles::Init(gHandles);DxeServices::Init();Ipc::Init();SystemServices::Init();DriverManager::Init();DeviceResourceBroker::Init();DriverGateway::Init();IsolationGuard::Init();UserHeap::Init();ForgePackageRegistry::Init();}
ObjectHandles::Table& HandlesForTest(){return gHandles;}
void RevokeProcessObjects(u64 owner){if(!owner)return;if(!IsolationGuard::BeginTeardown(owner))return;PciInterrupts::ReleaseProcess(owner);DriverGateway::RevokeProcess(owner);DeviceResourceBroker::RevokeProcess(owner);DriverManager::RevokeProcess(owner);SystemServices::UnregisterOwner(owner);Ipc::RevokeProcess(owner);DxeServices::RevokeProcess(owner);UserHeap::RevokeProcess(owner);ObjectHandles::RevokeProcess(gHandles,owner);IsolationGuard::FinishTeardown(owner);}
u64 RequiredCapability(u64 n){switch(n){case CreateWindow:case PresentWindow:return Dxe2::CapWindow;case OpenFile:case ReadFile:case ListDirectory:return Dxe2::CapFileRead;case WriteFile:return Dxe2::CapFileWrite;case CloseFile:return Dxe2::CapFileRead|Dxe2::CapFileWrite;case ServiceLookup:case IpcCreate:case IpcSend:case IpcReceive:case IpcClose:case ServiceRegister:case SpawnIsolated:case ForgeStoreRead:case ForgeStoreWrite:case ForgeRunReport:case ForgeRunQuery:case ForgePackageInstall:case ForgePackageRead:case ForgePackageRemove:case ForgePackageCount:case ForgePackageFetch:return Dxe2::CapIpc;case DriverRegister:case DriverClaimResource:case DriverReleaseResource:case DriverHeartbeat:case DriverMapMmio:case DriverPortRead:case DriverPortWrite:case DriverBindIrq:case DriverIdentity:case DriverResourceInfo:return Dxe2::CapDriverIo;case DriverAllocDma:case DriverFreeDma:return Dxe2::CapDma;case DriverConfigureMsi:return Dxe2::CapIrq;case DriverTakeOwnership:return Dxe2::CapDriverIo;default:return 0;}}
static bool permitted(u64 have,u64 need,u64 n){if(!need)return true;if(n==CloseFile)return (have&need)!=0;return (have&need)==need;}
Result Dispatch(const Frame&f){switch(f.number){case Yield:return {0,0};case Exit:return {(i64)f.arg0,0};default:return {-1,38};}}
static Result memerr(UserMemory::Result r){return r==UserMemory::Result::Ok?Result{0,0}:Result{-1,14};}
static struct {u64 pid;u32 status;u32 detail;} forgeRuns[64]{};
Result DispatchForProcess(const Frame&f,const Process::Image*p){
 const u64 need=RequiredCapability(f.number);if(need&&(!p||!p->dxe2||!permitted(p->grantedCapabilities,need,f.number)))return {-1,ErrorPermissionDenied};if(!p)return Dispatch(f);
 if(f.number==GetPid)return {(i64)p->id,0};
 if(f.number==SpawnIsolated){if(p->domain!=SecurityDomain::Kind::Application||f.arg0!=AppForgeRunner)return {-1,ErrorPermissionDenied};u64 pid=MultiAppRuntime::SpawnIsolatedFromKind(AppForgeRunner);return pid?Result{(i64)pid,0}:Result{-1,ErrorNoResources};}
 if(f.number==ForgeRunReport){if(p->domain!=SecurityDomain::Kind::SystemService)return {-1,ErrorPermissionDenied};for(auto&x:forgeRuns)if(!x.pid||x.pid==p->id){x={p->id,(u32)f.arg0,(u32)f.arg1};return {0,0};}return {-1,ErrorNoResources};}
 if(f.number==ForgeRunQuery){if(p->domain!=SecurityDomain::Kind::Application)return {-1,ErrorPermissionDenied};for(auto&x:forgeRuns)if(x.pid==f.arg0){u64 v=((u64)x.detail<<32)|x.status;if(x.status)x={0,0,0};return {(i64)v,0};}return {0,0};}
 if(f.number==ForgePackageCount){if(p->domain!=SecurityDomain::Kind::Application)return {-1,ErrorPermissionDenied};return {(i64)ForgePackageRegistry::Count(),0};}
 if(f.number==ForgePackageInstall){if(p->domain!=SecurityDomain::Kind::Application)return {-1,ErrorPermissionDenied};ForgePackageRegistry::Package q{};auto mr=UserMemory::CopyFromUser(*p,&q,f.arg0,sizeof(q));if(mr!=UserMemory::Result::Ok)return memerr(mr);return ForgePackageRegistry::Install(q)?Result{0,0}:Result{-1,22};}
 if(f.number==ForgePackageRead){if(p->domain!=SecurityDomain::Kind::Application)return {-1,ErrorPermissionDenied};ForgePackageRegistry::Package q{};if(!ForgePackageRegistry::Read((u32)f.arg0,q))return {-1,2};auto mr=UserMemory::CopyToUser(*p,f.arg1,&q,sizeof(q));return mr==UserMemory::Result::Ok?Result{(i64)sizeof(q),0}:memerr(mr);}
 if(f.number==ForgePackageRemove){if(p->domain!=SecurityDomain::Kind::Application)return {-1,ErrorPermissionDenied};return ForgePackageRegistry::Remove((u32)f.arg0)?Result{0,0}:Result{-1,2};}
 if(f.number==ForgePackageFetch){if(p->domain!=SecurityDomain::Kind::SystemService)return {-1,ErrorPermissionDenied};ForgePackageRegistry::Package q{};if(!ForgePackageRegistry::FetchLaunch(p->id,q))return {-1,2};auto mr=UserMemory::CopyToUser(*p,f.arg0,&q,sizeof(q));return mr==UserMemory::Result::Ok?Result{(i64)sizeof(q),0}:memerr(mr);}
 if(f.number==ForgeStoreRead||f.number==ForgeStoreWrite){
  // Brokered ForgeRunner-only private store. Durable UEFI NVRAM is preferred; RAM VFS is fallback.
  if(p->domain!=SecurityDomain::Kind::SystemService)return {-1,ErrorPermissionDenied};
  u32 app=(u32)f.arg0;u64 bytes=f.arg2;if(!app||!bytes||bytes>512)return {-1,22};u8 tmp[512];
  if(f.number==ForgeStoreWrite){auto mr=UserMemory::CopyFromUser(*p,tmp,f.arg1,bytes);if(mr!=UserMemory::Result::Ok)return memerr(mr);i64 pn=ForgePersistentStore::Write(app,tmp,bytes);if(pn>0)return {pn,0};}
  else{i64 pn=ForgePersistentStore::Read(app,tmp,bytes);if(pn>0){auto mr=UserMemory::CopyToUser(*p,f.arg1,tmp,(u64)pn);return mr==UserMemory::Result::Ok?Result{pn,0}:memerr(mr);}}
  // RAM-backed VFS fallback. The bytecode VM has no direct syscall primitive.
  char path[64]="/System/ForgeStore/";const char*hex="0123456789ABCDEF";u32 at=19;
  for(int sh=28;sh>=0;sh-=4)path[at++]=hex[(app>>sh)&15];path[at]=0;
  u32 rights=0;u32 flags=f.number==ForgeStoreWrite?(2u|4u|8u):1u;u64 id=DxeServices::OpenFileObject(0xF047Eull,path,flags,&rights);
  if(!id)return f.number==ForgeStoreRead?Result{0,0}:Result{-1,ErrorNoResources};i64 n=0;
  if(f.number==ForgeStoreWrite){auto mr=UserMemory::CopyFromUser(*p,tmp,f.arg1,bytes);if(mr!=UserMemory::Result::Ok){DxeServices::CloseFileObject(0xF047Eull,id);return memerr(mr);}n=DxeServices::WriteFileObject(0xF047Eull,id,tmp,bytes);}
  else{n=DxeServices::ReadFileObject(0xF047Eull,id,tmp,bytes);if(n>0){auto mr=UserMemory::CopyToUser(*p,f.arg1,tmp,(u64)n);if(mr!=UserMemory::Result::Ok){DxeServices::CloseFileObject(0xF047Eull,id);return memerr(mr);}}}
  DxeServices::CloseFileObject(0xF047Eull,id);return n<0?Result{-1,ErrorBadHandle}:Result{n,0};
 }
 if(f.number==CreateWindow){u64 id=DxeServices::CreateWindow(p->id,(i64)f.arg0,(i64)f.arg1,(i64)f.arg2,(i64)f.arg3);if(!id)return {-1,ErrorNoResources};u64 h=ObjectHandles::Create(gHandles,p->id,ObjectHandles::Type::Window,id,ObjectHandles::RightPresent|ObjectHandles::RightClose);if(!h){DxeServices::DestroyWindow(p->id,id);return {-1,ErrorNoResources};}return {(i64)h,0};}
 if(f.number==PresentWindow){auto*e=ObjectHandles::Resolve(gHandles,p->id,f.arg0,ObjectHandles::Type::Window,ObjectHandles::RightPresent);if(!e)return {-1,ErrorBadHandle};auto*sf=DxeServices::MutableWindowSurface(p->id,e->objectId);if(!sf)return {-1,ErrorBadHandle};u64 need=(u64)sf->width*(u64)sf->height*4ull;if(f.arg2!=need)return {-1,22};auto vr=UserMemory::ValidateRange(*p,f.arg1,need,UserMemory::Access::Read);if(vr!=UserMemory::Result::Ok)return memerr(vr);auto*go=GraphicsObjectManager::Find(p->id,sf->graphicsObjectId);if(!go||go->bytes<need)return {-1,ErrorBadHandle};auto mr=UserMemory::CopyFromUser(*p,(void*)(uptr)go->physical,f.arg1,need);if(mr!=UserMemory::Result::Ok)return memerr(mr);go->generation++;return DxeServices::PresentWindow(p->id,e->objectId)?Result{0,0}:Result{-1,ErrorBadHandle};}
 if(f.number==OpenFile){char path[DxeServices::MaxPath];u64 len=0;auto mr=UserMemory::CopyStringFromUser(*p,path,sizeof(path),f.arg0,&len);if(mr!=UserMemory::Result::Ok)return memerr(mr);u32 flags=(u32)f.arg1;if(flags&~15u)return {-1,22};if((flags&(2u|4u|8u))&&!(p->grantedCapabilities&Dxe2::CapFileWrite))return {-1,ErrorPermissionDenied};u32 rights=0;u64 id=DxeServices::OpenFileObject(p->id,path,flags,&rights);if(!id)return {-1,2};u64 h=ObjectHandles::Create(gHandles,p->id,ObjectHandles::Type::File,id,rights);if(!h){DxeServices::CloseFileObject(p->id,id);return {-1,ErrorNoResources};}return {(i64)h,0};}
 if(f.number==ReadFile){auto*e=ObjectHandles::Resolve(gHandles,p->id,f.arg0,ObjectHandles::Type::File,ObjectHandles::RightRead);if(!e)return {-1,ErrorBadHandle};u64 left=f.arg2,done=0;u8 buf[512];while(left){u64 ask=left>sizeof(buf)?sizeof(buf):left;i64 got=DxeServices::ReadFileObject(p->id,e->objectId,buf,ask);if(got<0)return {-1,ErrorBadHandle};if(!got)break;auto mr=UserMemory::CopyToUser(*p,f.arg1+done,buf,(u64)got);if(mr!=UserMemory::Result::Ok)return done?Result{(i64)done,0}:memerr(mr);done+=(u64)got;left-=(u64)got;if((u64)got<ask)break;}return {(i64)done,0};}
 if(f.number==WriteFile){auto*e=ObjectHandles::Resolve(gHandles,p->id,f.arg0,ObjectHandles::Type::File,ObjectHandles::RightWrite);if(!e)return {-1,ErrorBadHandle};u64 left=f.arg2,done=0;u8 buf[512];while(left){u64 ask=left>sizeof(buf)?sizeof(buf):left;auto mr=UserMemory::CopyFromUser(*p,buf,f.arg1+done,ask);if(mr!=UserMemory::Result::Ok)return done?Result{(i64)done,0}:memerr(mr);i64 put=DxeServices::WriteFileObject(p->id,e->objectId,buf,ask);if(put<0)return {-1,ErrorBadHandle};done+=(u64)put;left-=(u64)put;if((u64)put<ask)break;}return {(i64)done,0};}
 if(f.number==ServiceLookup){u64 endpoint=SystemServices::Lookup((u32)f.arg0);if(!endpoint)return {-1,2};u64 rights=ObjectHandles::RightSend;u64 h=ObjectHandles::Create(gHandles,p->id,ObjectHandles::Type::IpcEndpoint,endpoint,rights|ObjectHandles::RightClose);return h?Result{(i64)h,0}:Result{-1,ErrorNoResources};}
 if(f.number==IpcCreate){u32 requested=(u32)f.arg0;if(!requested||(requested&~(Ipc::RightSend|Ipc::RightReceive)))return {-1,22};u64 endpoint=Ipc::CreateEndpoint(p->id,requested);if(!endpoint)return {-1,ErrorNoResources};u32 rights=ObjectHandles::RightClose;if(requested&Ipc::RightSend)rights|=ObjectHandles::RightSend;if(requested&Ipc::RightReceive)rights|=ObjectHandles::RightReceive;u64 h=ObjectHandles::Create(gHandles,p->id,ObjectHandles::Type::IpcEndpoint,endpoint,rights);if(!h){Ipc::RevokeProcess(p->id);return {-1,ErrorNoResources};}return {(i64)h,0};}
 if(f.number==IpcSend){auto*e=ObjectHandles::Resolve(gHandles,p->id,f.arg0,ObjectHandles::Type::IpcEndpoint,ObjectHandles::RightSend);if(!e)return {-1,ErrorBadHandle};if(f.arg3>Ipc::MaxPayload)return {-1,22};u8 payload[Ipc::MaxPayload];if(f.arg3){auto mr=UserMemory::CopyFromUser(*p,payload,f.arg2,f.arg3);if(mr!=UserMemory::Result::Ok)return memerr(mr);}return Ipc::Send(p->id,e->objectId,(u32)f.arg1,payload,(u32)f.arg3)?Result{0,0}:Result{-1,11};}
 if(f.number==IpcReceive){auto*e=ObjectHandles::Resolve(gHandles,p->id,f.arg0,ObjectHandles::Type::IpcEndpoint,ObjectHandles::RightReceive);if(!e)return {-1,ErrorBadHandle};struct Wire{u64 sender;u32 type;u32 bytes;u8 payload[Ipc::MaxPayload];} w{};u64 sender=0;u32 type=0;i64 n=Ipc::Receive(p->id,e->objectId,&sender,&type,w.payload,Ipc::MaxPayload);if(n<0)return {-1,11};if(n==0)return {0,0};w.sender=sender;w.type=type;w.bytes=(u32)n;auto mr=UserMemory::CopyToUser(*p,f.arg1,&w,sizeof(w));if(mr!=UserMemory::Result::Ok)return memerr(mr);return {n,0};}
 if(f.number==IpcClose){auto*e=ObjectHandles::Resolve(gHandles,p->id,f.arg0,ObjectHandles::Type::IpcEndpoint,ObjectHandles::RightClose);if(!e)return {-1,ErrorBadHandle};return ObjectHandles::Close(gHandles,p->id,f.arg0)?Result{0,0}:Result{-1,ErrorBadHandle};}
 if(f.number==ServiceRegister){if(!SecurityPolicy::CanRegisterSystemService(p->domain))return {-1,ErrorPermissionDenied};auto*e=ObjectHandles::Resolve(gHandles,p->id,f.arg1,ObjectHandles::Type::IpcEndpoint,ObjectHandles::RightReceive);if(!e)return {-1,ErrorBadHandle};return SystemServices::Register((u32)f.arg0,p->id,e->objectId)?Result{0,0}:Result{-1,ErrorNoResources};}
 if(f.number==ListDirectory){char path[DxeServices::MaxPath];u64 len=0;auto mr=UserMemory::CopyStringFromUser(*p,path,sizeof(path),f.arg0,&len);if(mr!=UserMemory::Result::Ok)return memerr(mr);u64 cap=f.arg2;if(cap>2048)cap=2048;if(!cap)return {0,0};u8 tmp[2048];i64 got=DxeServices::ListDirectory(path,tmp,cap);if(got<0)return {-1,2};mr=UserMemory::CopyToUser(*p,f.arg1,tmp,(u64)got);if(mr!=UserMemory::Result::Ok)return memerr(mr);return {got,0};}
 if(f.number==DriverIdentity){if(p->domain!=SecurityDomain::Kind::Driver)return {-1,ErrorPermissionDenied};u64 dev=DriverManager::AssignedDevice(p->id);return dev?Result{(i64)dev,0}:Result{-1,ErrorBadHandle};}
 if(f.number==DriverResourceInfo){if(p->domain!=SecurityDomain::Kind::Driver)return {-1,ErrorPermissionDenied};u64 dev=DriverManager::AssignedDevice(p->id);if(!dev)return {-1,ErrorBadHandle};u32 want=(u32)f.arg0,seen=0;for(auto&r:DeviceResourceBroker::state.resources)if(r.active&&r.deviceId==dev){if(seen++!=want)continue;struct Info{u64 id,base,length;u32 type,rights;u32 reserved;}info{r.id,r.base,r.length,(u32)r.type,r.rights,0};auto mr=UserMemory::CopyToUser(*p,f.arg1,&info,sizeof(info));if(mr!=UserMemory::Result::Ok)return memerr(mr);return {(i64)seen,0};}return {0,0};}
 if(f.number==DriverAllocDma){if(p->domain!=SecurityDomain::Kind::Driver)return {-1,ErrorPermissionDenied};struct Info{u64 user,physical,bytes;}info{};u64 u=0,ph=0;if(!DriverGateway::AllocateDma(*p,f.arg0,f.arg1,&u,&ph))return {-1,ErrorNoResources};info={u,ph,f.arg0};auto mr=UserMemory::CopyToUser(*p,f.arg2,&info,sizeof(info));if(mr!=UserMemory::Result::Ok){DriverGateway::FreeDma(*p,u);return memerr(mr);}return {0,0};}
 if(f.number==DriverFreeDma){if(p->domain!=SecurityDomain::Kind::Driver)return {-1,ErrorPermissionDenied};return DriverGateway::FreeDma(*p,f.arg0)?Result{0,0}:Result{-1,ErrorBadHandle};}
 if(f.number==DriverConfigureMsi){auto*e=ObjectHandles::Resolve(gHandles,p->id,f.arg0,ObjectHandles::Type::DeviceResource,ObjectHandles::RightDevice);if(!e)return {-1,ErrorBadHandle};auto*r=DeviceResourceBroker::FindMutable(e->objectId);u8 v=0;if(!r||!PciInterrupts::ConfigureMsi(*p,*r,&v))return {-1,ErrorPermissionDenied};return {(i64)v,0};}
 if(f.number==DriverTakeOwnership){if(p->domain!=SecurityDomain::Kind::Driver)return {-1,ErrorPermissionDenied};u64 dev=DriverManager::AssignedDevice(p->id);if(!dev||dev!=f.arg0)return {-1,ErrorBadHandle};Pci::State ps{};Pci::Scan(ps);bool xhci=false;for(u32 i=0;i<ps.count;i++){auto&d=ps.devices[i];u64 id=0xD000000000000000ull|((u64)d.vendor<<32)|((u64)d.device<<16)|((u64)d.bus<<8)|((u64)d.slot<<3)|d.function;if(id==dev&&d.classCode==0x0c&&d.subclass==0x03&&d.progIf==0x30){xhci=true;break;}}if(!xhci)return {-1,ErrorPermissionDenied};return UsbRuntime::RelinquishToRing3()?Result{0,0}:Result{-1,ErrorPermissionDenied};}
 if(f.number==DriverRegister){IsolationGuard::Admit(*p);if(!IsolationGuard::MayUsePrivilegedDriverPath(*p))return {-1,ErrorPermissionDenied};if(p->domain!=SecurityDomain::Kind::Driver)return {-1,ErrorPermissionDenied};return DriverManager::Register(*const_cast<Process::Image*>(p),f.arg0)?Result{0,0}:Result{-1,ErrorNoResources};}
 if(f.number==DriverClaimResource){IsolationGuard::Admit(*p);if(!IsolationGuard::MayUsePrivilegedDriverPath(*p))return {-1,ErrorPermissionDenied};if(p->domain!=SecurityDomain::Kind::Driver)return {-1,ErrorPermissionDenied};u32 rights=(u32)f.arg1;if(!DeviceResourceBroker::Claim(*p,f.arg0,rights))return {-1,ErrorPermissionDenied};u64 h=ObjectHandles::Create(gHandles,p->id,ObjectHandles::Type::DeviceResource,f.arg0,ObjectHandles::RightDevice|ObjectHandles::RightClose);if(!h){DeviceResourceBroker::Release(*p,f.arg0);return {-1,ErrorNoResources};}return {(i64)h,0};}
 if(f.number==DriverReleaseResource){auto*e=ObjectHandles::Resolve(gHandles,p->id,f.arg0,ObjectHandles::Type::DeviceResource,ObjectHandles::RightDevice);if(!e)return {-1,ErrorBadHandle};if(!DeviceResourceBroker::Release(*p,e->objectId))return {-1,ErrorPermissionDenied};return ObjectHandles::Close(gHandles,p->id,f.arg0)?Result{0,0}:Result{-1,ErrorBadHandle};}
 if(f.number==DriverHeartbeat){if(p->domain!=SecurityDomain::Kind::Driver)return {-1,ErrorPermissionDenied};return DriverManager::Heartbeat(*p,f.arg0)?Result{0,0}:Result{-1,ErrorBadHandle};}
 if(f.number==DriverMapMmio){auto*e=ObjectHandles::Resolve(gHandles,p->id,f.arg0,ObjectHandles::Type::DeviceResource,ObjectHandles::RightDevice);if(!e)return {-1,ErrorBadHandle};u64 va=0;return DriverGateway::MapMmio(*p,e->objectId,&va)?Result{(i64)va,0}:Result{-1,ErrorPermissionDenied};}
 if(f.number==DriverPortRead){auto*e=ObjectHandles::Resolve(gHandles,p->id,f.arg0,ObjectHandles::Type::DeviceResource,ObjectHandles::RightDevice);if(!e)return {-1,ErrorBadHandle};u32 v=0;return DriverGateway::PortRead(*p,e->objectId,f.arg1,(u32)f.arg2,&v)?Result{(i64)v,0}:Result{-1,ErrorPermissionDenied};}
 if(f.number==DriverPortWrite){auto*e=ObjectHandles::Resolve(gHandles,p->id,f.arg0,ObjectHandles::Type::DeviceResource,ObjectHandles::RightDevice);if(!e)return {-1,ErrorBadHandle};return DriverGateway::PortWrite(*p,e->objectId,f.arg1,(u32)f.arg2,(u32)f.arg3)?Result{0,0}:Result{-1,ErrorPermissionDenied};}
 if(f.number==DriverBindIrq){auto*re=ObjectHandles::Resolve(gHandles,p->id,f.arg0,ObjectHandles::Type::DeviceResource,ObjectHandles::RightDevice);auto*ie=ObjectHandles::Resolve(gHandles,p->id,f.arg1,ObjectHandles::Type::IpcEndpoint,ObjectHandles::RightReceive);if(!re||!ie)return {-1,ErrorBadHandle};return DriverGateway::BindIrq(*p,re->objectId,ie->objectId)?Result{0,0}:Result{-1,ErrorPermissionDenied};}
 if(f.number==AllocMemory){u64 va=UserHeap::Allocate(*p,f.arg0);return va?Result{(i64)va,0}:Result{-1,ErrorNoResources};}
 if(f.number==FreeMemory){return UserHeap::Free(*p,f.arg0)?Result{0,0}:Result{-1,ErrorBadHandle};}
 if(f.number==CloseFile){auto*e=ObjectHandles::Resolve(gHandles,p->id,f.arg0,ObjectHandles::Type::File,ObjectHandles::RightClose);if(!e)return {-1,ErrorBadHandle};u64 id=e->objectId;if(!DxeServices::CloseFileObject(p->id,id)||!ObjectHandles::Close(gHandles,p->id,f.arg0))return {-1,ErrorBadHandle};return {0,0};}
 return Dispatch(f);
}
}
