#include "Tcp.hpp"
namespace Davis::Tcp {
State state{}; static void w16(u8*p,u16 v){p[0]=v>>8;p[1]=v;} static void w32(u8*p,u32 v){p[0]=v>>24;p[1]=v>>16;p[2]=v>>8;p[3]=v;} static u16 r16(const u8*p){return (u16)((u16)p[0]<<8|p[1]);} static u32 r32(const u8*p){return ((u32)p[0]<<24)|((u32)p[1]<<16)|((u32)p[2]<<8)|p[3];}
static bool eq(Net::Ipv4 a,Net::Ipv4 b){for(u32 i=0;i<4;i++)if(a.b[i]!=b.b[i])return false;return true;}
void Init(){state={};state.ready=true;}
void Release(Socket&s){if(!s.used)return;s={};}
static u16 tcpChecksum(Net::Ipv4 s,Net::Ipv4 d,const u8*t,u32 n){u32 sum=0;auto add=[&](u16 v){sum+=v;while(sum>>16)sum=(sum&0xffff)+(sum>>16);};add((u16)((u16)s.b[0]<<8|s.b[1]));add((u16)((u16)s.b[2]<<8|s.b[3]));add((u16)((u16)d.b[0]<<8|d.b[1]));add((u16)((u16)d.b[2]<<8|d.b[3]));add(6);add((u16)n);u32 i=0;for(;i+1<n;i+=2)add((u16)((u16)t[i]<<8|t[i+1]));if(i<n)add((u16)t[i]<<8);return (u16)~sum;}
static bool segment(Socket&s,u8 flags,const void*data,u32 n,Net::Packet&o){if(n>MaxPayload)return false;o={};u32 tcp=20+n,total=20+tcp;if(14+total>Net::MaxFrame)return false;o.bytes=14+total;for(u32 i=0;i<6;i++){o.data[i]=s.remoteMac.b[i];o.data[6+i]=Net::state.config.mac.b[i];}w16(o.data+12,0x0800);u8*ip=o.data+14;ip[0]=0x45;w16(ip+2,(u16)total);w16(ip+4,Net::state.nextIpId++);w16(ip+6,0x4000);ip[8]=64;ip[9]=6;for(u32 i=0;i<4;i++){ip[12+i]=Net::state.config.address.b[i];ip[16+i]=s.remoteIp.b[i];}w16(ip+10,Net::Checksum16(ip,20));u8*t=ip+20;w16(t,s.localPort);w16(t+2,s.remotePort);w32(t+4,s.sendNext);w32(t+8,s.recvNext);t[12]=0x50;t[13]=flags;w16(t+14,4096);if(data)for(u32 i=0;i<n;i++)t[20+i]=((const u8*)data)[i];w16(t+16,tcpChecksum(Net::state.config.address,s.remoteIp,t,tcp));state.segmentsTx++;return true;}
Socket* Open(Net::Ipv4 ip,Net::Mac mac,u16 port){if(!Net::state.config.configured)return nullptr;for(auto&s:state.sockets)if(!s.used){s={};s.used=true;s.phase=Phase::SynSent;s.remoteIp=ip;s.remoteMac=mac;s.remotePort=port;s.localPort=Net::state.nextEphemeral++;s.sendNext=0xD1500000u+(u32)state.opens*4099u;s.sendUnacked=s.sendNext;s.remoteWindow=4096;state.opens++;return &s;}return nullptr;}
bool BuildPending(Socket&s,Net::Packet&o){if(!s.used)return false;if(s.pendingRetransmit){s.pendingRetransmit=false;u32 cur=s.sendNext;s.sendNext=s.sendUnacked;bool ok=segment(s,s.lastFlags,s.lastBytes?s.lastPayload:nullptr,s.lastBytes,o);s.sendNext=cur;return ok;}if(s.phase==Phase::SynSent){s.lastFlags=0x02;s.lastBytes=0;return segment(s,0x02,nullptr,0,o);}if(s.pendingAck){s.pendingAck=false;return segment(s,0x10,nullptr,0,o);}return false;}
bool SendData(Socket&s,const void*d,u32 n,Net::Packet&o){if(s.phase!=Phase::Established||!n)return false;if(!segment(s,0x18,d,n,o))return false;s.sendUnacked=s.sendNext;s.sendNext+=n;s.retransmitTicks=0;s.lastFlags=0x18;s.lastBytes=n;for(u32 i=0;i<n;i++)s.lastPayload[i]=((const u8*)d)[i];return true;}
bool Close(Socket&s,Net::Packet&o){if(s.phase!=Phase::Established)return false;if(!segment(s,0x11,nullptr,0,o))return false;s.sendUnacked=s.sendNext;s.sendNext++;s.phase=Phase::FinWait;return true;}
void OnFrame(const u8*f,u32 n){if(!f||n<54||r16(f+12)!=0x0800)return;const u8*ip=f+14;u32 ihl=(ip[0]&15)*4;if((ip[0]>>4)!=4||ihl<20||ip[9]!=6||14+ihl+20>n)return;u16 total=r16(ip+2);if(total<ihl+20||14+total>n)return;
 // Fail closed on corrupt/fragmented IPv4 TCP packets until reassembly exists.
 if(Net::Checksum16(ip,ihl)!=0)return;u16 frag=r16(ip+6);if((frag&0x3fffu)!=0)return;Net::Ipv4 src{},dst{};for(u32 i=0;i<4;i++){src.b[i]=ip[12+i];dst.b[i]=ip[16+i];}
 // Packets for another local address must never be delivered to a socket.
 if(Net::state.config.configured&&!eq(dst,Net::state.config.address))return;const u8*t=ip+ihl;u32 thl=(t[12]>>4)*4;if(thl<20||thl>60||ihl+thl>total)return;u16 sp=r16(t),dp=r16(t+2);Socket*s=nullptr;for(auto&x:state.sockets)if(x.used&&x.localPort==dp&&x.remotePort==sp&&eq(x.remoteIp,src)){s=&x;break;}if(!s)return;u16 saved=r16(t+16);u8 temp[MaxPayload+60]{};u32 tn=total-ihl;if(tn>sizeof(temp))return;for(u32 i=0;i<tn;i++)temp[i]=t[i];temp[16]=temp[17]=0;if(tcpChecksum(src,dst,temp,tn)!=saved){state.checksumErrors++;return;}state.segmentsRx++;u32 seq=r32(t+4),ack=r32(t+8);u8 fl=t[13];u32 payload=total-ihl-thl;if(fl&0x04){s->phase=Phase::Failed;state.resets++;return;}if(s->phase==Phase::SynSent&&(fl&0x12)==0x12&&ack==s->sendNext+1){s->recvNext=seq+1;s->sendNext++;s->sendUnacked=s->sendNext;s->phase=Phase::Established;s->retries=0;s->pendingAck=true;return;}if(fl&0x10){if(ack>s->sendUnacked&&ack<=s->sendNext)s->sendUnacked=ack;}if(payload&&seq==s->recvNext){u32 room=MaxReceive-s->receiveBytes,copy=payload<room?payload:room;for(u32 i=0;i<copy;i++)s->receive[s->receiveBytes+i]=t[thl+i];s->receiveBytes+=copy;s->recvNext+=payload;s->pendingAck=true;}if(fl&0x01){s->recvNext++;s->pendingAck=true;s->peerClosed=true;s->phase=(s->phase==Phase::FinWait)?Phase::Closed:Phase::CloseWait;}}
void Tick(){for(auto&s:state.sockets)if(s.used&&(s.phase==Phase::SynSent||s.sendUnacked<s.sendNext)){if(++s.retransmitTicks>500){s.retransmitTicks=0;if(++s.retries>5)s.phase=Phase::Failed;else {s.pendingRetransmit=true;state.retransmits++;}}}}
}
