#include "TimerRuntime.hpp"
#include "../Arch/x86_64/Cpu.hpp"
namespace Davis::TimerRuntime {
void Init(State&s){s={};s.phase=Phase::Cold;}
bool Validate(State&s,const TimerActivation::State&a,const TimerPlatform::State&p,const LocalApicTimer::State&t,const InterruptController::State&ic,const Preemption::State&pre,const TimeReference::State&tr){if(!TimerActivation::Validate(a,p,t,ic,pre)||!tr.usable){s.phase=Phase::Failed;return false;}s.phase=Phase::Validated;return true;}
void Rollback(State&s,TimerActivation::State&a,TimerPlatform::State&p,LocalApicTimer::State&t){Cpu::DisableInterrupts();LocalApicTimer::Stop(t);p.interruptsEnabled=false;TimerActivation::MarkFailed(a);s.rollbackPerformed=true;s.phase=Phase::RolledBack;}
bool Activate(State&s,TimerActivation::State&a,TimerPlatform::State&p,LocalApicTimer::State&t,Preemption::State&pre,const TimeReference::State&tr){if(s.phase!=Phase::Validated||!tr.usable){s.phase=Phase::Failed;return false;}s.interruptsBefore=pre.timerInterrupts;LocalApicTimer::Arm(t);if(!t.armed){Rollback(s,a,p,t);return false;}TimerActivation::MarkArmed(a,TimeReference::ReadTsc(),s.interruptsBefore);p.phase=TimerPlatform::Phase::Armed;p.interruptsEnabled=true;Cpu::EnableInterrupts();s.phase=Phase::InterruptsLive;return true;}
bool Verify(State&s,TimerActivation::State&a,TimerPlatform::State&p,LocalApicTimer::State&t,Preemption::State&pre,const TimeReference::State&tr){if(s.phase!=Phase::InterruptsLive||!tr.usable){Rollback(s,a,p,t);return false;}const u64 deadline=TimeReference::ReadTsc()+(tr.tscHz*(u64)a.health.graceMilliseconds)/1000ull;while(TimeReference::ReadTsc()<deadline&&pre.timerInterrupts==s.interruptsBefore)Cpu::Pause();s.interruptsAfter=pre.timerInterrupts;if(!PreemptionHealth::Observe(a.health,TimeReference::ReadTsc(),tr.tscHz,s.interruptsAfter)||!PreemptionHealth::Healthy(a.health)){Rollback(s,a,p,t);return false;}s.phase=Phase::Healthy;return true;}
void ResetAfterSlice(State&s,TimerActivation::State&a,TimerPlatform::State&p,LocalApicTimer::State&t){Cpu::DisableInterrupts();LocalApicTimer::Stop(t);p.interruptsEnabled=false;if(p.phase==TimerPlatform::Phase::Armed)p.phase=TimerPlatform::Phase::Calibrated;a.result=TimerActivation::Result::NotReady;s.phase=Phase::Validated;}
}
