#include "UsbRuntime.hpp"
#include "XhciControl.hpp"
#include "KernelMemory.hpp"
namespace Davis::UsbRuntime {
State state{};
void Init(){state={};state.bringup=Bringup::Cold;Pci::Scan(state.pci);state.bringup=Bringup::PciScanned;if(!Xhci::Discover(state.xhci,state.pci)){state.result=Result::NoController;return;}state.bringup=Bringup::Discovered;if(!Xhci::ReadCapabilities(state.xhci)){state.result=Result::CapabilitiesFailed;return;}state.bringup=Bringup::Capabilities;Xhci::InitDma(state.dma);if(!Xhci::AllocateDmaStructures(state.dma,state.xhci,KernelMemory::allocator)){state.result=Result::DmaFailed;return;}state.bringup=Bringup::DmaAllocated;Xhci::InitCommandRing(state.dma);Xhci::InitController(state.controller);state.bringup=Bringup::StartEntered;if(Xhci::StartController(state.xhci,state.dma,state.controller)!=Xhci::StartResult::Ok){state.result=Result::StartFailed;return;}state.bringup=Bringup::Started;Xhci::InitEnumeration(state.enumeration);state.bringup=Bringup::Enumerating;
 Xhci::PortState ps{};Xhci::ScanPorts(state.xhci,state.controller,ps);bool any=false;
 for(u32 i=0;i<ps.count;i++){if(!ps.ports[i].connected)continue;state.connectedPorts++;auto r=Xhci::EnumeratePort(state.xhci,state.controller,state.dma,KernelMemory::allocator,state.enumeration,ps.ports[i].port);if(r!=Xhci::EnumResult::Ok)continue;any=true;Xhci::SlotResources*sr=nullptr;for(auto&x:state.enumeration.slots)if(x.active&&x.port==ps.ports[i].port){sr=&x;break;}auto*dev=sr?Usb::FindPort(state.enumeration.usb,sr->port):nullptr;if(!dev||!sr)continue;if(Xhci::ReadAndConfigureDescriptors(state.xhci,state.controller,state.dma,*sr,KernelMemory::allocator,*dev)!=Xhci::ControlResult::Ok)continue;state.lastVendor=dev->vendorId;state.lastProduct=dev->productId;if(Xhci::ConfigureBootHid(state.xhci,state.controller,state.dma,*sr,KernelMemory::allocator,*dev)==Xhci::ControlResult::Ok){state.hidDevices++;if(sr->hidProtocol==1)state.keyboards++;else if(sr->hidProtocol==2)state.mice++;}}
 state.ready=true;state.bringup=Bringup::Ready;state.result=any?Result::Addressed:Result::NoDevice;}
bool RelinquishToRing3(){/* v1.93 recovery: do not strand USB input. Ring-3 ownership remains disabled until the driver can prove controller/HID readiness before commit. */ state.ring3Owned=false;return false;}
bool PollHid(UsbHid::Keyboard& k,UsbHid::Mouse& m,char& key,bool& mouseChanged){key=0;mouseChanged=false;state.polls++;if(state.ring3Owned||!state.ready)return false;bool active=false;
 for(auto&r:state.enumeration.slots){if(!r.active||!r.hidReady)continue;active=true;if(r.hidQueued)continue;auto*ring=(Xhci::Trb*)r.hidRing.virtualAddress;u32 i=r.hidIndex;u64 b=r.hidBuffer.physical;ring[i].parameterLo=(u32)b;ring[i].parameterHi=(u32)(b>>32);ring[i].status=r.hidReportBytes;ring[i].control=(1u<<5)|(1u<<10)|(r.hidCycle?1u:0u);if(++r.hidIndex==255){ring[255].parameterLo=(u32)r.hidRing.physical;ring[255].parameterHi=(u32)(r.hidRing.physical>>32);ring[255].status=0;ring[255].control=(6u<<10)|2u|(r.hidCycle?1u:0u);r.hidIndex=0;r.hidCycle=!r.hidCycle;}__asm__ __volatile__("":::"memory");volatile u32*db=(volatile u32*)(uptr)(state.xhci.mmio+(state.xhci.dboff&~3u)+(u32)r.slotId*4u);*db=r.hidDci;r.hidQueued=true;}
 auto&e=Xhci::EventTrbs(state.dma)[state.dma.eventIndex];if((e.control&1u)!=(state.dma.eventCycle?1u:0u))return active;u32 type=(e.control>>10)&0x3f;u8 slot=(u8)(e.control>>24),dci=(u8)((e.control>>16)&0x1f),cc=(u8)(e.status>>24);state.events++;state.lastCompletion=cc;state.lastSlot=slot;state.lastDci=dci;if(++state.dma.eventIndex==256){state.dma.eventIndex=0;state.dma.eventCycle=!state.dma.eventCycle;}volatile u64*erdp=(volatile u64*)(uptr)(state.xhci.mmio+(state.xhci.rtsoff&~0x1fu)+0x38);*erdp=(state.dma.eventRing.physical+(u64)state.dma.eventIndex*sizeof(Xhci::Trb))|(1ull<<3);
 if(type==32){for(auto&r:state.enumeration.slots){if(!r.active||!r.hidReady||slot!=r.slotId||dci!=r.hidDci)continue;if(cc==1||cc==13){state.reports++;auto*b=(u8*)r.hidBuffer.virtualAddress;if(r.hidProtocol==1){char q=UsbHid::DecodeBootKeyboard(k,b);if(q)key=q;}else if(r.hidProtocol==2){UsbHid::DecodeBootMouse(m,b,r.hidReportBytes);mouseChanged=true;}r.hidQueued=false;}break;}}
 return active;}

}
