#include "XhciControl.hpp"
namespace Davis::Xhci {
static constexpr u32 TypeShift=10, SetupType=2, DataType=3, StatusType=4, TransferEventType=32, EvaluateContextType=13;
static inline void Barrier(){__asm__ __volatile__("" ::: "memory");}
static inline void RingSlotDoorbell(const State&s,u8 slot){volatile u32*db=(volatile u32*)(uptr)(s.mmio+(s.dboff&~3u)+(u32)slot*4u);*db=1;Barrier();}
static void AdvanceEvent(const State&s,DmaState&d){if(++d.eventIndex==256){d.eventIndex=0;d.eventCycle=!d.eventCycle;}volatile u64*erdp=(volatile u64*)(uptr)(s.mmio+(s.rtsoff&~0x1fu)+0x38);*erdp=(d.eventRing.physical+(u64)d.eventIndex*sizeof(Trb))|(1ull<<3);Barrier();}
static bool PollTransfer(const State&s,DmaState&d,u8 slot,u32 spins,TransferCompletion&o){o={};while(spins--){Trb*e=&EventTrbs(d)[d.eventIndex];u32 ctl=e->control;if((ctl&1u)!=(d.eventCycle?1u:0u)){__asm__ __volatile__("pause");continue;}u32 type=(ctl>>TypeShift)&0x3f;u8 eslot=(u8)(ctl>>24),ep=(u8)((ctl>>16)&0x1f),cc=(u8)(e->status>>24);u32 residual=e->status&0xFFFFFFu;AdvanceEvent(s,d);if(type!=TransferEventType||eslot!=slot)continue;o={cc,eslot,ep,residual};return true;}return false;}
static bool QueueControl(SlotResources&r,u64 buffer,u16 bytes,u8 request,u16 value,u16 index,bool in,u8 requestType=0){if(!r.active||r.ep0Index>252)return false;Trb*t=(Trb*)r.ep0Ring.virtualAddress;auto put=[&](u64 p,u32 st,u32 ctl){u32 i=r.ep0Index;t[i].parameterLo=(u32)p;t[i].parameterHi=(u32)(p>>32);t[i].status=st;t[i].control=(ctl&~1u)|(r.ep0Cycle?1u:0u);if(++r.ep0Index==255){t[255].parameterLo=(u32)r.ep0Ring.physical;t[255].parameterHi=(u32)(r.ep0Ring.physical>>32);t[255].status=0;t[255].control=(6u<<TypeShift)|2u|(r.ep0Cycle?1u:0u);r.ep0Index=0;r.ep0Cycle=!r.ep0Cycle;}};
 u64 setup=(u64)(requestType|(in?0x80u:0u))|((u64)request<<8)|((u64)value<<16)|((u64)index<<32)|((u64)bytes<<48);u32 trt=bytes?(in?3u:2u):0u;put(setup,8,(SetupType<<TypeShift)|(3u<<6)|(trt<<16));if(bytes)put(buffer,bytes,(DataType<<TypeShift)|(in?(1u<<16):0u));put(0,0,(StatusType<<TypeShift)|(1u<<5)|(in?0u:(1u<<16)));Barrier();return true;}
ControlResult GetDescriptor(const State&s,const ControllerState&c,DmaState&d,SlotResources&r,Memory::PageAllocator&a,u8 dt,u8 di,u16 lang,void*out,u16 bytes,u32 spins){if(!c.running||!d.valid||!r.active||!out||!bytes)return ControlResult::InvalidState;auto b=Memory::AllocDma(a,bytes,64);if(!b.physical)return ControlResult::NoResources;for(u16 i=0;i<bytes;i++)((u8*)b.virtualAddress)[i]=0;if(!QueueControl(r,b.physical,bytes,6,(u16)(((u16)dt<<8)|di),lang,true)){Memory::FreeDma(a,b);return ControlResult::RingFull;}RingSlotDoorbell(s,r.slotId);TransferCompletion tc{};if(!PollTransfer(s,d,r.slotId,spins,tc)){Memory::FreeDma(a,b);return ControlResult::Timeout;}if(tc.completionCode!=1&&tc.completionCode!=13){Memory::FreeDma(a,b);return ControlResult::TransferError;}u32 got=bytes;if(tc.residual<got)got-=tc.residual;else got=0;for(u32 i=0;i<got;i++)((u8*)out)[i]=((u8*)b.virtualAddress)[i];Memory::FreeDma(a,b);return got?ControlResult::Ok:ControlResult::TransferError;}
static ControlResult EvaluateEp0(const State&s,const ControllerState&c,DmaState&d,SlotResources&r,u16 mps,u32 spins){u32 cs=(s.hcc1&(1u<<2))?64u:32u;u8*ic=(u8*)r.inputContext.virtualAddress;for(u32 i=0;i<cs*33;i++)ic[i]=0;*(u32*)(ic+4)=2u;u8*ep0=ic+cs*2;*(u32*)(ep0+4)=(3u<<1)|(4u<<3)|((u32)mps<<16);u64 dq=r.ep0Ring.physical|1ull;*(u32*)(ep0+8)=(u32)dq;*(u32*)(ep0+12)=(u32)(dq>>32);Barrier();u64 p=0;CommandCompletion cc{};if(!QueueCommand(d,r.inputContext.physical,0,(EvaluateContextType<<TypeShift)|((u32)r.slotId<<24),p)||RingDoorbell0(s,c)!=CommandResult::Ok||!PollCommandCompletion(s,d,p,cc,spins)||cc.result!=CommandResult::Ok)return ControlResult::EvaluateFailed;r.ep0MaxPacket=mps;return ControlResult::Ok;}
ControlResult ReadAndConfigureDescriptors(const State&s,const ControllerState&c,DmaState&d,SlotResources&r,Memory::PageAllocator&a,Usb::Device&dev,u32 spins){u8 first[8]{};auto cr=GetDescriptor(s,c,d,r,a,1,0,0,first,8,spins);if(cr!=ControlResult::Ok)return cr;if(first[0]<8||first[1]!=1)return ControlResult::BadDescriptor;u16 mps=first[7];if(r.speedId>=4)mps=(u16)(1u<<first[7]);if(!mps)return ControlResult::BadDescriptor;if(mps!=r.ep0MaxPacket){cr=EvaluateEp0(s,c,d,r,mps,spins);if(cr!=ControlResult::Ok)return cr;}u8 dd[18]{};cr=GetDescriptor(s,c,d,r,a,1,0,0,dd,18,spins);if(cr!=ControlResult::Ok||!Usb::ParseDeviceDescriptor(dev,dd,18))return ControlResult::BadDescriptor;u8 ch[9]{};cr=GetDescriptor(s,c,d,r,a,2,0,0,ch,9,spins);if(cr!=ControlResult::Ok||ch[0]<9||ch[1]!=2)return ControlResult::BadDescriptor;u16 total=(u16)ch[2]|((u16)ch[3]<<8);if(total<9||total>4096)return ControlResult::BadDescriptor;auto cfg=Memory::AllocDma(a,total,64);if(!cfg.physical)return ControlResult::NoResources;cr=GetDescriptor(s,c,d,r,a,2,0,0,cfg.virtualAddress,total,spins);if(cr==ControlResult::Ok&&!Usb::ParseConfiguration(dev,(const u8*)cfg.virtualAddress,total))cr=ControlResult::BadDescriptor;Memory::FreeDma(a,cfg);if(cr==ControlResult::Ok)dev.state=Usb::DeviceState::Configured;return cr;}
static ControlResult NoDataRequest(const State&s,const ControllerState&c,DmaState&d,SlotResources&r,u8 request,u16 value,u16 index,u32 spins,u8 requestType=0){
 if(!c.running||!d.valid||!r.active)return ControlResult::InvalidState;
 if(!QueueControl(r,0,0,request,value,index,false,requestType))return ControlResult::RingFull;
 RingSlotDoorbell(s,r.slotId);TransferCompletion tc{};if(!PollTransfer(s,d,r.slotId,spins,tc))return ControlResult::Timeout;
 return tc.completionCode==1?ControlResult::Ok:ControlResult::TransferError;
}
ControlResult ConfigureBootHid(const State&s,const ControllerState&c,DmaState&d,SlotResources&r,Memory::PageAllocator&a,Usb::Device&dev,u32 spins){
 Usb::Interface* hi=nullptr;Usb::Endpoint* ep=nullptr;
 for(u32 i=0;i<dev.interfaceCount&&!hi;i++){auto&in=dev.interfaces[i];if(in.valid&&in.klass==3&&(in.protocol==1||in.protocol==2)){for(u32 j=0;j<in.endpointCount;j++){auto&e=in.endpoints[j];if(e.valid&&(e.address&0x80)&&((e.attributes&3)==3)){hi=&in;ep=&e;break;}}}}
 if(!hi||!ep)return ControlResult::BadDescriptor;
 auto cr=NoDataRequest(s,c,d,r,9,dev.configuration,0,spins);if(cr!=ControlResult::Ok)return cr; // SET_CONFIGURATION
 (void)NoDataRequest(s,c,d,r,11,0,hi->number,spins,0x21); // HID SET_PROTOCOL(boot), class/interface request; tolerate devices that stall it
 u8 epnum=ep->address&0x0f;u8 dci=(u8)(epnum*2+1);if(dci<3||dci>31)return ControlResult::BadDescriptor;
 r.hidRing=Memory::AllocDma(a,4096,64);r.hidReportBytes=(hi->protocol==1)?8:4;r.hidBuffer=Memory::AllocDma(a,r.hidReportBytes,64);
 if(!r.hidRing.physical||!r.hidBuffer.physical)return ControlResult::NoResources;r.hidIndex=0;r.hidCycle=true;r.hidDci=dci;r.hidProtocol=hi->protocol;r.hidReady=false;r.hidQueued=false;
 u32 cs=(s.hcc1&(1u<<2))?64u:32u;u8*ic=(u8*)r.inputContext.virtualAddress;for(u32 i=0;i<cs*33;i++)ic[i]=0;
 *(u32*)(ic+4)=1u|(1u<<dci); // add Slot Context + interrupt endpoint contextu8*slotc=ic+cs;*(u32*)(slotc+0)=((u32)r.speedId<<20)|((u32)dci<<27);*(u32*)(slotc+4)=(u32)r.port<<16;
 u8*ec=ic+cs*(dci+1);u16 mps=ep->maxPacket?ep->maxPacket:r.hidReportBytes;u32 interval=ep->interval?ep->interval:1;if(interval>16)interval=16;
 *(u32*)(ec+0)=((interval-1)&0xffu)<<16;*(u32*)(ec+4)=(3u<<1)|(7u<<3)|((u32)mps<<16);u64 dq=r.hidRing.physical|1ull;*(u32*)(ec+8)=(u32)dq;*(u32*)(ec+12)=(u32)(dq>>32);*(u32*)(ec+16)=mps;
 Barrier();u64 phys=0;CommandCompletion cc{};if(!QueueCommand(d,r.inputContext.physical,0,(12u<<TypeShift)|((u32)r.slotId<<24),phys)||RingDoorbell0(s,c)!=CommandResult::Ok||!PollCommandCompletion(s,d,phys,cc,spins)||cc.result!=CommandResult::Ok)return ControlResult::EvaluateFailed;
 r.hidReady=true;return ControlResult::Ok;
}

}
